Data Collection

restaurants in Auckland
cafes in Auckland
tourist attractions in Auckland
parks in Auckland
shopping malls in Auckland

In [2]:
pip install requests pandas python-dotenv

Requirement already satisfied: requests in c:\users\arjun\anaconda3\lib\site-packages (2.32.2)
Requirement already satisfied: pandas in c:\users\arjun\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: python-dotenv in c:\users\arjun\anaconda3\lib\site-packages (0.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\arjun\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\arjun\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\arjun\anaconda3\lib\site-packages (from requests) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\arjun\anaconda3\lib\site-packages (from requests) (2024.7.4)
Requirement already satisfied: numpy>=1.26.0 in c:\users\arjun\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\arjun\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\arjun\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\arjun\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\arjun\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [57]:
# %pip install python-dotenv requests pandas

import os, time, json, math, requests
from pathlib import Path
from dotenv import load_dotenv
import pandas as pd

# Load .env
load_dotenv()
API_KEY = os.getenv("GOOGLE_API_KEY")
assert API_KEY, "GOOGLE_API_KEY missing"

# Data folders
Path("data/raw").mkdir(parents=True, exist_ok=True)
Path("data/processed").mkdir(parents=True, exist_ok=True)

# Your 5 categories
PLACE_TYPES = ["restaurant", "cafe", "tourist attraction", "park", "shopping mall"]
CITY = "Auckland"

In [59]:
BASE_TEXT_SEARCH = "https://maps.googleapis.com/maps/api/place/textsearch/json"

def text_search(query, pagetoken=None):
    params = {
        "query": query,
        "key": API_KEY,
    }
    if pagetoken:
        params["pagetoken"] = pagetoken
    r = requests.get(BASE_TEXT_SEARCH, params=params, timeout=30)
    r.raise_for_status()
    return r.json()

def collect_places_for_query(query, max_pages=5, sleep_between=2.0):
    """
    Pull up to max_pages of results for a given text query.
    Returns a list of place dicts with minimal fields.
    """
    places = []
    token = None
    for page in range(max_pages):
        if token:
            time.sleep(sleep_between)  # necessary delay for next_page_token
        data = text_search(query, pagetoken=token)

        results = data.get("results", [])
        for p in results:
            places.append({
                "place_id": p.get("place_id"),
                "name": p.get("name"),
                "lat": (p.get("geometry", {}).get("location", {}) or {}).get("lat"),
                "lng": (p.get("geometry", {}).get("location", {}) or {}).get("lng"),
                "address": p.get("formatted_address"),
                "rating": p.get("rating"),
                "user_ratings_total": p.get("user_ratings_total"),
                "business_status": p.get("business_status"),
                "types": ",".join(p.get("types", [])),
                "source_query": query,
            })
        token = data.get("next_page_token")
        if not token:
            break
    return places

In [61]:
all_places = []
for t in PLACE_TYPES:
    q = f"{t} in {CITY}"
    print("Fetching:", q)
    chunk = collect_places_for_query(q, max_pages=5)  # tune pages up/down
    all_places.extend(chunk)
    print(f"  found {len(chunk)} rows so far, total={len(all_places)}")

# Deduplicate by place_id
df_places = pd.DataFrame(all_places)
df_places = df_places.dropna(subset=["place_id"]).drop_duplicates(subset=["place_id"]).reset_index(drop=True)
print("Unique places:", len(df_places))

df_places.head(3)

Fetching: restaurant in Auckland
  found 60 rows so far, total=60
Fetching: cafe in Auckland
  found 60 rows so far, total=120
Fetching: tourist attraction in Auckland
  found 60 rows so far, total=180
Fetching: park in Auckland
  found 60 rows so far, total=240
Fetching: shopping mall in Auckland
  found 60 rows so far, total=300
Unique places: 283

,place_id,name,lat,lng,address,rating,user_ratings_total,business_status,types,source_query
0,ChIJF2_wv4lHDW0R47WKR5aSdmE,Onslow,-36.847685,174.769957,"9 Princes Street, Auckland Central, Auckland 1...",4.8,1289.0,OPERATIONAL,"restaurant,food,point_of_interest,establishment",restaurant in Auckland
1,ChIJKWPi4S5HDW0R-Ao9My5Mf48,Gilt Brasserie,-36.847655,174.767196,"2 Chancery Street, Chambers, Auckland 1010, Ne...",4.6,613.0,OPERATIONAL,"restaurant,food,point_of_interest,establishment",restaurant in Auckland
2,ChIJjz8Dgf5HDW0RcKfgUZdV8fw,Amano,-36.844412,174.770464,"66 - 68, Tyler Street, Britomart Place, Auckla...",4.6,4358.0,OPERATIONAL,"restaurant,bakery,food,store,point_of_interest...",restaurant in Auckland

In [67]:
df_places.to_csv("data/processed/auckland_places_basic.csv", index=False)

In [69]:
BASE_PLACE_DETAILS = "https://maps.googleapis.com/maps/api/place/details/json"

DETAIL_FIELDS = (
    "name,place_id,geometry/location,formatted_address,types,"
    "rating,user_ratings_total,international_phone_number,website,opening_hours,"
    "reviews"  # includes up to 5 reviews if available
)

def place_details(place_id):
    params = {
        "place_id": place_id,
        "fields": DETAIL_FIELDS,
        "key": API_KEY,
    }
    r = requests.get(BASE_PLACE_DETAILS, params=params, timeout=30)
    r.raise_for_status()
    return r.json()

def enrich_places_with_details(df, limit=None, sleep_between=0.15):
    """
    For each place, call details and collect: richer fields + reviews (up to 5).
    limit: for quick pilot (e.g., 100). None = all rows.
    """
    rows = df.to_dict(orient="records")
    if limit:
        rows = rows[:limit]

    enriched = []
    reviews = []

    for i, p in enumerate(rows, start=1):
        pid = p["place_id"]
        try:
            d = place_details(pid)
            status = d.get("status")
            result = d.get("result") or {}
            if status != "OK":
                print("Details not OK:", pid, status)
                continue

            # merge/enrich
            enriched.append({
                "place_id": pid,
                "name": result.get("name") or p.get("name"),
                "lat": (result.get("geometry", {}).get("location", {}) or {}).get("lat") or p.get("lat"),
                "lng": (result.get("geometry", {}).get("location", {}) or {}).get("lng") or p.get("lng"),
                "address": result.get("formatted_address") or p.get("address"),
                "types": ",".join(result.get("types", [])) or p.get("types"),
                "rating": result.get("rating"),
                "user_ratings_total": result.get("user_ratings_total"),
                "phone": result.get("international_phone_number"),
                "website": result.get("website"),
                "opening_hours_present": "opening_hours" in result,
                "source_query": p.get("source_query"),
            })

            # capture up to 5 reviews (if present)
            for rv in (result.get("reviews") or []):
                reviews.append({
                    "place_id": pid,
                    "author_name": rv.get("author_name"),
                    "rating": rv.get("rating"),
                    "text": rv.get("text"),
                    "time": rv.get("time"),  # unix epoch seconds
                    "relative_time": rv.get("relative_time_description"),
                    "language": rv.get("language"),
                    "profile_photo_url": rv.get("profile_photo_url"),
                })

        except Exception as e:
            print("Error details for", pid, "→", e)

        if i % 25 == 0:
            print(f"Processed {i}/{len(rows)}")
        time.sleep(sleep_between)

    return pd.DataFrame(enriched), pd.DataFrame(reviews)

In [71]:
# Pilot run
df_places_details_pilot, df_reviews_pilot = enrich_places_with_details(df_places, limit=100)
print(df_places_details_pilot.shape, df_reviews_pilot.shape)

# Save pilot snapshots
df_places_details_pilot.to_csv("data/processed/auckland_places_details_pilot.csv", index=False)
df_reviews_pilot.to_csv("data/processed/auckland_reviews_pilot.csv", index=False)

Processed 25/100
Processed 50/100
Processed 75/100
Processed 100/100
(100, 12) (500, 8)

In [72]:
df_places_details_all, df_reviews_all = enrich_places_with_details(df_places, limit=None)
df_places_details_all.to_csv("data/processed/auckland_places_details.csv", index=False)
df_reviews_all.to_csv("data/processed/auckland_reviews.csv", index=False)

df_places_details_all.head(3), df_reviews_all.head(3)

Processed 25/283
Processed 50/283
Processed 75/283
Processed 100/283
Processed 125/283
Processed 150/283
Processed 175/283
Processed 200/283
Processed 225/283
Processed 250/283
Processed 275/283

(                      place_id            name        lat         lng  \
 0  ChIJF2_wv4lHDW0R47WKR5aSdmE          Onslow -36.847685  174.769957
 1  ChIJKWPi4S5HDW0R-Ao9My5Mf48  Gilt Brasserie -36.847655  174.767196
 2  ChIJjz8Dgf5HDW0RcKfgUZdV8fw           Amano -36.844412  174.770464

                                              address  \
 0  9 Princes Street, Auckland Central, Auckland 1...
 1  2 Chancery Street, Chambers, Auckland 1010, Ne...
 2  66 - 68, Tyler Street, Britomart Place, Auckla...

                                                types  rating  \
 0    establishment,food,point_of_interest,restaurant     4.8
 1    establishment,food,point_of_interest,restaurant     4.6
 2  bakery,establishment,food,point_of_interest,re...     4.6

    user_ratings_total           phone                    website  \
 0              1289.0  +64 9 930 9123      http://www.onslow.nz/
 1               613.0  +64 9 300 3126  https://giltbrasserie.nz/
 2              4358.0  +64 9 394 1416  https://savor.co.nz/amano

    opening_hours_present            source_query
 0                   True  restaurant in Auckland
 1                   True  restaurant in Auckland
 2                   True  restaurant in Auckland  ,
                       place_id      author_name  rating  \
 0  ChIJF2_wv4lHDW0R47WKR5aSdmE        Kiwi Kiwi       5
 1  ChIJF2_wv4lHDW0R47WKR5aSdmE  Jennie Goldsack       5
 2  ChIJF2_wv4lHDW0R47WKR5aSdmE       Anna Giang       5

                                                 text        time  \
 0  Fabulous Food!\nEnjoyed an outstanding food pe...  1754804453
 1  We were welcomed warmly. We felt like we were ...  1750235479
 2  Amazing dinner with great service and excellen...  1754733790

       relative_time language  \
 0  in the last week       en
 1       a month ago       en
 2  in the last week       en

                                    profile_photo_url
 0  https://lh3.googleusercontent.com/a-/ALV-UjUZw...
 1  https://lh3.googleusercontent.com/a/ACg8ocLvW9...
 2  https://lh3.googleusercontent.com/a-/ALV-UjUYk...  )

In [ ]:
import pandas as pd
import numpy as np
import hashlib
from datetime import datetime, timezone

# If you already have these from the previous cells:
# df_places_details_pilot, df_reviews_pilot
# or for the full run: df_places_details_all, df_reviews_all

# Use whichever you have in memory; fall back to CSVs if needed
def load_latest():
    try:
        return df_places_details_all.copy(), df_reviews_all.copy()
    except NameError:
        pass
    try:
        return df_places_details_pilot.copy(), df_reviews_pilot.copy()
    except NameError:
        pass
    # load from disk if needed
    p = pd.read_csv("data/processed/auckland_places_details.csv")
    r = pd.read_csv("data/processed/auckland_reviews.csv")
    return p, r

places_raw, reviews_raw = load_latest()
print(places_raw.shape, reviews_raw.shape)

# ---- Places: tidy types, category, dtypes, dedupe
places = places_raw.copy()

# derive a simple "category" from the source_query (e.g., "restaurant in Auckland")
def extract_category(s):
    if pd.isna(s): return None
    return s.split(" in ")[0].strip().lower()

if "source_query" in places.columns:
    places["category"] = places["source_query"].map(extract_category)
else:
    places["category"] = np.nan

# fix dtypes
for col in ["lat","lng","rating"]:
    if col in places.columns:
        places[col] = pd.to_numeric(places[col], errors="coerce")

if "user_ratings_total" in places.columns:
    places["user_ratings_total"] = pd.to_numeric(places["user_ratings_total"], errors="coerce").fillna(0).astype(int)

# dedupe by place_id
places = places.dropna(subset=["place_id"]).drop_duplicates(subset=["place_id"]).reset_index(drop=True)

# keep essential columns (add/remove to taste)
keep_cols_places = ["place_id","name","lat","lng","address","category","types","rating","user_ratings_total","phone","website","opening_hours_present"]
places = places[[c for c in keep_cols_places if c in places.columns]]

print("Places cleaned:", places.shape)
places.head(3)

# ---- Reviews: convert time, add stable review_id, drop empties
reviews = reviews_raw.copy()

# Some places have no reviews; drop empty text rows
reviews["text"] = reviews["text"].fillna("").astype(str).str.strip()
reviews = reviews[reviews["text"] != ""]

# Convert epoch seconds to UTC datetime (if field is present/epoch-like)
if "time" in reviews.columns:
    reviews["time"] = pd.to_numeric(reviews["time"], errors="coerce")
    reviews["publish_time_utc"] = reviews["time"].map(
        lambda x: datetime.fromtimestamp(x, tz=timezone.utc) if pd.notna(x) else None
    )
else:
    reviews["publish_time_utc"] = pd.NaT

# make a stable review_id (hash of place_id + time + first 32 chars of text)
def make_review_id(row):
    base = f"{row.get('place_id','')}|{row.get('time','')}|{(row.get('text','')[:32])}"
    return hashlib.sha256(base.encode("utf-8")).hexdigest()[:24]

reviews["review_id"] = reviews.apply(make_review_id, axis=1)

# normalize rating dtype
if "rating" in reviews.columns:
    reviews["rating"] = pd.to_numeric(reviews["rating"], errors="coerce")

# keep essential columns
keep_cols_reviews = ["review_id","place_id","author_name","rating","text","publish_time_utc","language"]
reviews = reviews[[c for c in keep_cols_reviews if c in reviews.columns]]

# drop duplicates (rare but possible if API returned same review multiple times)
reviews = reviews.drop_duplicates(subset=["review_id"]).reset_index(drop=True)

print("Reviews cleaned:", reviews.shape)
reviews.head(3)

In [ ]:
# Coverage stats
print("Total places:", len(places))
print("Total reviews:", len(reviews))
print("Places with ≥1 review:", reviews["place_id"].nunique())

# Missing coordinates?
missing_coords = places[places["lat"].isna() | places["lng"].isna()]
print("Places missing lat/lng:", len(missing_coords))

# Category distribution
print(places["category"].value_counts(dropna=False).head(10))

# Review languages (Google often provides 'language')
if "language" in reviews.columns:
    print(reviews["language"].value_counts(dropna=False).head(10))

# Are any place_ids in reviews not found in places?
orphans = set(reviews["place_id"]) - set(places["place_id"])
print("Orphan reviews (no matching place):", len(orphans))

In [ ]:
Path("data/final").mkdir(parents=True, exist_ok=True)
places.to_csv("data/final/places.csv", index=False)
reviews.to_csv("data/final/reviews.csv", index=False)

print("Saved:", "data/final/places.csv", "and", "data/final/reviews.csv")

In [75]:
# === DROP-IN CELL: Top-up categories with low review counts ===
# %pip install requests pandas python-dotenv

import os, time, requests, pandas as pd
from pathlib import Path
from dotenv import load_dotenv

# ----------------------- Config -----------------------
load_dotenv()
API_KEY = os.getenv("GOOGLE_API_KEY")
assert API_KEY, "GOOGLE_API_KEY missing. Load your .env first."

CITY = "Auckland"
REVIEW_THRESHOLD_PER_CATEGORY = 150     # <-- adjust to your target
TEXTSEARCH_PAGES = 3                    # up to ~60 results per query
TEXTSEARCH_DELAY_FOR_NEXT_TOKEN = 2.0   # seconds; Google needs a pause before next_page_token works
DETAILS_DELAY = 0.15                    # seconds between Place Details calls

# Files
Path("data/processed").mkdir(parents=True, exist_ok=True)
PLACES_BASIC_CSV   = "data/processed/auckland_places_basic.csv"
PLACES_DETAILS_CSV = "data/processed/auckland_places_details.csv"
REVIEWS_CSV        = "data/processed/auckland_reviews.csv"

# Suburbs to widen coverage (edit as needed)
SUBURBS = [
    "Auckland CBD","Parnell","Newmarket","Grafton","Ponsonby","Grey Lynn","Freemans Bay",
    "Mt Eden","Epsom","Onehunga","Ellerslie","Greenlane","Remuera","Meadowbank","St Heliers",
    "Mission Bay","Kohimarama","Orakei","Panmure","Glen Innes","Mt Wellington","Sylvia Park",
    "Avondale","New Lynn","Henderson","Te Atatu","Massey","Hobsonville","Albany","Rosedale",
    "Takapuna","Milford","Devonport","Bayswater","Belmont","Northcote","Birkenhead","Glenfield",
    "Manukau","Papatoetoe","Mangere","Otara","Botany Downs","Howick","Pakuranga","Beachlands"
]

# Five categories in your scope
CATEGORIES = ["restaurant","cafe","tourist attraction","park","shopping mall"]

# Keyword variants to broaden each category without changing your stored category
VARIANTS = {
    "restaurant": ["restaurant","eatery","dining"],
    "cafe": ["cafe","coffee shop","espresso"],
    "tourist attraction": ["tourist attraction","landmark","sightseeing"],
    "park": ["park","regional park"],
    "shopping mall": ["shopping mall","shopping centre"]
}

# ----------------------- Helpers -----------------------
BASE_TEXT_SEARCH   = "https://maps.googleapis.com/maps/api/place/textsearch/json"
BASE_PLACE_DETAILS = "https://maps.googleapis.com/maps/api/place/details/json"
DETAIL_FIELDS = (
    "name,place_id,geometry/location,formatted_address,types,"
    "rating,user_ratings_total,international_phone_number,website,opening_hours,"
    "reviews"  # up to 5 reviews
)

def text_search(query, pagetoken=None):
    params = {"query": query, "key": API_KEY}
    if pagetoken: params["pagetoken"] = pagetoken
    r = requests.get(BASE_TEXT_SEARCH, params=params, timeout=30)
    r.raise_for_status()
    return r.json()

def collect_places_for_query(query, max_pages=3, sleep_between=2.0):
    places = []
    token = None
    for _ in range(max_pages):
        if token:
            time.sleep(sleep_between)
        data = text_search(query, pagetoken=token)
        for p in data.get("results", []):
            places.append({
                "place_id": p.get("place_id"),
                "name": p.get("name"),
                "lat": (p.get("geometry", {}).get("location", {}) or {}).get("lat"),
                "lng": (p.get("geometry", {}).get("location", {}) or {}).get("lng"),
                "address": p.get("formatted_address"),
                "rating": p.get("rating"),
                "user_ratings_total": p.get("user_ratings_total"),
                "business_status": p.get("business_status"),
                "types": ",".join(p.get("types", [])),
                "source_query": query,
            })
        token = data.get("next_page_token")
        if not token:
            break
    return places

def place_details(place_id):
    params = {"place_id": place_id, "fields": DETAIL_FIELDS, "key": API_KEY}
    r = requests.get(BASE_PLACE_DETAILS, params=params, timeout=30)
    r.raise_for_status()
    return r.json()

def extract_category_from_source(q):
    if pd.isna(q): return None
    return q.split(" in ")[0].replace("near ", "").strip().lower()

def infer_category_from_types(types_str):
    if pd.isna(types_str): return None
    t = [x.strip().lower() for x in str(types_str).split(",")]
    if "restaurant" in t: return "restaurant"
    if "cafe" in t or "café" in t: return "cafe"
    if "tourist_attraction" in t or "tourist attraction" in t: return "tourist attraction"
    if "park" in t: return "park"
    if "shopping_mall" in t or "shopping mall" in t: return "shopping mall"
    return None

# ----------------------- Load current data -----------------------
def load_csv(path, cols=None):
    if not Path(path).exists():
        return pd.DataFrame(columns=cols or [])
    return pd.read_csv(path)

places_basic   = load_csv(PLACES_BASIC_CSV)
places_details = load_csv(PLACES_DETAILS_CSV)
reviews        = load_csv(REVIEWS_CSV)

# Derive category for places_details
if "category" not in places_details.columns:
    if "source_query" in places_details.columns:
        places_details["category"] = places_details["source_query"].apply(extract_category_from_source)
    elif "types" in places_details.columns:
        places_details["category"] = places_details["types"].apply(infer_category_from_types)
    else:
        places_details["category"] = None

# Baseline counts BEFORE top-up
def by_cat_places(df):
    return (df.dropna(subset=["place_id"])
              .drop_duplicates("place_id")
              .groupby("category")["place_id"].nunique()
              .sort_values(ascending=False))

def by_cat_reviews(rev, places_df):
    tmp = rev.merge(places_df[["place_id","category"]], on="place_id", how="left")
    # review_id might not exist yet; fall back to counting rows
    key = "review_id" if "review_id" in tmp.columns else tmp.columns[0]
    return tmp.groupby("category")[key].count().sort_values(ascending=False)

baseline_places = by_cat_places(places_details)
baseline_reviews = by_cat_reviews(reviews, places_details)

print("=== Baseline (before top-up) ===")
print("Places by category:\n", baseline_places.fillna(0), "\n")
print("Reviews by category:\n", baseline_reviews.fillna(0), "\n")

# Which categories are below the threshold?
underfilled = [c for c in CATEGORIES if baseline_reviews.get(c, 0) < REVIEW_THRESHOLD_PER_CATEGORY]
print("Categories under threshold (", REVIEW_THRESHOLD_PER_CATEGORY, "reviews ): ", underfilled)

if not underfilled:
    print("All categories meet the threshold. Nothing to top-up.")
else:
    # ----------------------- Suburb sweep for underfilled categories -----------------------
    new_chunks = []
    for cat in underfilled:
        variants = VARIANTS.get(cat, [cat])
        for area in SUBURBS:
            for v in variants:
                q = f"{v} near {area}, {CITY}"
                chunk = collect_places_for_query(q, max_pages=TEXTSEARCH_PAGES, sleep_between=TEXTSEARCH_DELAY_FOR_NEXT_TOKEN)
                new_chunks.extend(chunk)

    df_new_basic = (pd.DataFrame(new_chunks)
                    .dropna(subset=["place_id"])
                    .drop_duplicates("place_id")
                    .reset_index(drop=True))

    # Merge with existing basic list
    if not places_basic.empty:
        df_basic_merged = (pd.concat([places_basic, df_new_basic], ignore_index=True)
                              .dropna(subset=["place_id"])
                              .drop_duplicates("place_id")
                              .reset_index(drop=True))
    else:
        df_basic_merged = df_new_basic.copy()

    # ----------------------- Details only for new place_ids -----------------------
    existing_ids = set(places_details["place_id"]) if not places_details.empty else set()
    candidate_ids = [pid for pid in df_basic_merged["place_id"].tolist() if pid not in existing_ids]

    print(f"New unique place_ids to enrich: {len(candidate_ids)}")
    enriched, rev_rows = [], []

    for i, pid in enumerate(candidate_ids, start=1):
        try:
            d = place_details(pid)
            if d.get("status") != "OK":
                continue
            res = d.get("result", {})
            enriched.append({
                "place_id": pid,
                "name": res.get("name"),
                "lat": (res.get("geometry", {}).get("location", {}) or {}).get("lat"),
                "lng": (res.get("geometry", {}).get("location", {}) or {}).get("lng"),
                "address": res.get("formatted_address"),
                "types": ",".join(res.get("types", [])),
                "rating": res.get("rating"),
                "user_ratings_total": res.get("user_ratings_total"),
                "phone": res.get("international_phone_number"),
                "website": res.get("website"),
                "opening_hours_present": "opening_hours" in res,
                # keep the original category based on query where possible
                "source_query": "topup",  # tag so we know this came from the sweep
            })
            for rv in (res.get("reviews") or []):
                rev_rows.append({
                    "place_id": pid,
                    "author_name": rv.get("author_name"),
                    "rating": rv.get("rating"),
                    "text": rv.get("text"),
                    "time": rv.get("time"),
                    "relative_time": rv.get("relative_time_description"),
                    "language": rv.get("language"),
                })
        except Exception as e:
            print("details error", pid, "→", e)
        if i % 50 == 0:
            print(f"Details processed: {i}/{len(candidate_ids)}")
        time.sleep(DETAILS_DELAY)

    df_enriched_new = pd.DataFrame(enriched)
    df_reviews_new  = pd.DataFrame(rev_rows)

    # Derive category for new enriched rows (from types best-effort)
    if not df_enriched_new.empty:
        df_enriched_new["category"] = df_enriched_new["types"].apply(infer_category_from_types)

    # Merge with existing details and reviews; dedupe
    if not df_enriched_new.empty:
        places_details_updated = (pd.concat([places_details, df_enriched_new], ignore_index=True)
                                     .dropna(subset=["place_id"])
                                     .drop_duplicates("place_id")
                                     .reset_index(drop=True))
    else:
        places_details_updated = places_details.copy()

    if not df_reviews_new.empty:
        # create a simple review_id if missing
        if "review_id" not in df_reviews_new.columns:
            import hashlib
            df_reviews_new["text"] = df_reviews_new["text"].fillna("")
            df_reviews_new["review_id"] = df_reviews_new.apply(
                lambda r: hashlib.sha256(f"{r.get('place_id','')}|{r.get('time','')}|{r.get('text','')[:32]}".encode("utf-8")).hexdigest()[:24],
                axis=1
            )
        reviews_updated = (pd.concat([reviews, df_reviews_new], ignore_index=True)
                             .dropna(subset=["place_id"])
                             .drop_duplicates(subset=["review_id"] if "review_id" in reviews.columns else None)
                             .reset_index(drop=True))
    else:
        reviews_updated = reviews.copy()

    # Save updated CSVs
    df_basic_merged.to_csv(PLACES_BASIC_CSV, index=False)
    places_details_updated.to_csv(PLACES_DETAILS_CSV, index=False)
    reviews_updated.to_csv(REVIEWS_CSV, index=False)

    # ----------------------- Fresh totals (AFTER top-up) -----------------------
    # Recompute category for places_details in case some rows lacked it
    if "category" not in places_details_updated.columns or places_details_updated["category"].isna().all():
        places_details_updated["category"] = places_details_updated["types"].apply(infer_category_from_types)

    after_places  = by_cat_places(places_details_updated)
    after_reviews = by_cat_reviews(reviews_updated, places_details_updated)

    print("\n=== After top-up ===")
    print("Places by category:\n", after_places.fillna(0), "\n")
    print("Reviews by category:\n", after_reviews.fillna(0), "\n")

    # Deltas
    delta_places  = (after_places.fillna(0)  - baseline_places.fillna(0)).sort_values(ascending=False)
    delta_reviews = (after_reviews.fillna(0) - baseline_reviews.fillna(0)).sort_values(ascending=False)
    print("Δ Places by category:\n", delta_places, "\n")
    print("Δ Reviews by category:\n", delta_reviews, "\n")

print("Done.")

=== Baseline (before top-up) ===
Places by category:
 category
restaurant            60
shopping mall         60
tourist attraction    60
cafe                  57
park                  46
Name: place_id, dtype: int64

Reviews by category:
 category
restaurant            300
tourist attraction    293
shopping mall         291
cafe                  285
park                  229
Name: place_id, dtype: int64

Categories under threshold ( 150 reviews ):  []
All categories meet the threshold. Nothing to top-up.
Done.

In [77]:
# === DROP-IN CELL: Scale up via grid-based Nearby Search (v1) ===
# %pip install requests pandas python-dotenv

import os, time, math, requests, pandas as pd
from pathlib import Path
from dotenv import load_dotenv

# ----------------------- Config -----------------------
load_dotenv()
API_KEY = os.getenv("GOOGLE_API_KEY")
assert API_KEY, "GOOGLE_API_KEY missing. Load your .env first."

# Auckland rough bounds (tweak if desired)
LAT_MIN, LAT_MAX = -37.10, -36.60
LON_MIN, LON_MAX = 174.40, 175.10

# Grid spacing (~km): 0.009 deg lat ≈ 1 km; 0.011 deg lon ≈ ~1 km near Auckland
LAT_STEP = 0.018   # ≈ 2 km
LON_STEP = 0.022   # ≈ 2 km
RADIUS_M = 1500    # 1.5 km circle per grid point

# Place types (v1 names)
PLACE_TYPES = ["restaurant","cafe","tourist_attraction","park","shopping_mall"]

# Throttle & paging
NEARBY_PAGE_SIZE = 20
NEARBY_SLEEP = 0.35   # seconds between requests - increase if you hit quotas
DETAILS_SLEEP = 0.15  # seconds between details calls
MAX_PAGES_PER_CENTER = 4  # up to ~80 results per center/type if available

# Files
Path("data/processed").mkdir(parents=True, exist_ok=True)
PLACES_BASIC_CSV   = "data/processed/auckland_places_basic.csv"
PLACES_DETAILS_CSV = "data/processed/auckland_places_details.csv"
REVIEWS_CSV        = "data/processed/auckland_reviews.csv"

# ----------------------- Helpers -----------------------
def nearby_search_v1(lat, lng, included_type, page_token=None):
    """
    Places API v1 Nearby Search (POST).
    Returns minimal fields; include nextPageToken in field mask.
    """
    url = "https://places.googleapis.com/v1/places:searchNearby"
    headers = {
        "Content-Type": "application/json",
        "X-Goog-FieldMask": "places.id,places.displayName,places.location,places.formattedAddress,places.types,nextPageToken",
    }
    params = {"key": API_KEY}
    payload = {
        "includedTypes": [included_type],
        "maxResultCount": NEARBY_PAGE_SIZE,
        "locationRestriction": {
            "circle": {"center": {"latitude": lat, "longitude": lng}, "radius": RADIUS_M}
        }
    }
    if page_token:
        payload["pageToken"] = page_token
    r = requests.post(url, headers=headers, params=params, json=payload, timeout=30)
    r.raise_for_status()
    return r.json()

def crawl_grid_for_type(place_type, centers):
    seen_ids = set()
    rows = []
    for (lat, lon) in centers:
        token = None
        for _ in range(MAX_PAGES_PER_CENTER):
            data = nearby_search_v1(lat, lon, place_type, token)
            for p in data.get("places", []):
                pid = p.get("id")
                if pid and pid not in seen_ids:
                    seen_ids.add(pid)
                    rows.append({
                        "place_id": pid,
                        "name": (p.get("displayName") or {}).get("text"),
                        "lat": (p.get("location") or {}).get("latitude"),
                        "lng": (p.get("location") or {}).get("longitude"),
                        "address": p.get("formattedAddress"),
                        "types": ",".join(p.get("types", [])),
                        "source_query": place_type,  # keep track of type
                    })
            token = data.get("nextPageToken")
            if not token:
                break
            time.sleep(NEARBY_SLEEP)
        time.sleep(NEARBY_SLEEP)
    return rows

# Classic Place Details (keeps your review format consistent with earlier code)
BASE_PLACE_DETAILS = "https://maps.googleapis.com/maps/api/place/details/json"
DETAIL_FIELDS = (
    "name,place_id,geometry/location,formatted_address,types,"
    "rating,user_ratings_total,international_phone_number,website,opening_hours,"
    "reviews"  # up to 5 reviews
)
def place_details_classic(place_id):
    params = {"place_id": place_id, "fields": DETAIL_FIELDS, "key": API_KEY}
    r = requests.get(BASE_PLACE_DETAILS, params=params, timeout=30)
    r.raise_for_status()
    return r.json()

def infer_category_from_types(types_str):
    if pd.isna(types_str): return None
    t = [x.strip().lower() for x in str(types_str).split(",")]
    if "restaurant" in t: return "restaurant"
    if "cafe" in t or "café" in t: return "cafe"
    if "tourist_attraction" in t or "tourist attraction" in t: return "tourist attraction"
    if "park" in t: return "park"
    if "shopping_mall" in t or "shopping mall" in t: return "shopping mall"
    return None

def by_cat_places(df):
    if df.empty: return pd.Series(dtype=int)
    tmp = df.dropna(subset=["place_id"]).drop_duplicates("place_id")
    if "category" not in tmp.columns or tmp["category"].isna().all():
        tmp["category"] = tmp["types"].apply(infer_category_from_types)
    return tmp.groupby("category")["place_id"].nunique().sort_values(ascending=False)

def by_cat_reviews(rev, places_df):
    if rev.empty: return pd.Series(dtype=int)
    # try to join to categories
    tmp = rev.merge(places_df[["place_id","types"]], on="place_id", how="left")
    tmp["category"] = tmp["types"].apply(infer_category_from_types)
    key = "review_id" if "review_id" in tmp.columns else tmp.columns[0]
    return tmp.groupby("category")[key].count().sort_values(ascending=False)

# ----------------------- Build grid of centers -----------------------
lats = []
lat = LAT_MIN
while lat <= LAT_MAX:
    lats.append(round(lat, 6))
    lat += LAT_STEP
lons = []
lon = LON_MIN
while lon <= LON_MAX:
    lons.append(round(lon, 6))
    lon += LON_STEP

centers = [(la, lo) for la in lats for lo in lons]
print(f"Grid points: {len(centers)} (lat steps={len(lats)}, lon steps={len(lons)})")
est_calls = len(centers) * len(PLACE_TYPES)
print(f"Est. Nearby calls (no paging): ~{est_calls}. With paging up to {MAX_PAGES_PER_CENTER}x per center.")

# ----------------------- Load existing CSVs -----------------------
def load_csv(path, cols=None):
    if not Path(path).exists(): return pd.DataFrame(columns=cols or [])
    return pd.read_csv(path)

places_basic   = load_csv(PLACES_BASIC_CSV)
places_details = load_csv(PLACES_DETAILS_CSV)
reviews        = load_csv(REVIEWS_CSV)

baseline_places_cat  = by_cat_places(places_details)
baseline_reviews_cat = by_cat_reviews(reviews, places_details)
print("\n=== Baseline (details+reviews) ===")
print("Places by category:\n", baseline_places_cat.fillna(0), "\n")
print("Reviews by category:\n", baseline_reviews_cat.fillna(0), "\n")

# ----------------------- Crawl grid by type -----------------------
all_rows = []
for t in PLACE_TYPES:
    print("Crawling type:", t)
    rows = crawl_grid_for_type(t, centers)
    all_rows.extend(rows)
    print(f"  Collected {len(rows)} rows for {t}")

df_grid = (pd.DataFrame(all_rows)
           .dropna(subset=["place_id"])
           .drop_duplicates("place_id")
           .reset_index(drop=True))

print("Unique places from grid:", df_grid["place_id"].nunique())

# Merge with existing basic (Text Search) list and save
if not places_basic.empty:
    places_basic_merged = (pd.concat([places_basic, df_grid], ignore_index=True)
                           .dropna(subset=["place_id"])
                           .drop_duplicates("place_id")
                           .reset_index(drop=True))
else:
    places_basic_merged = df_grid.copy()

places_basic_merged.to_csv(PLACES_BASIC_CSV, index=False)
print("Saved merged basic list →", PLACES_BASIC_CSV)

# ----------------------- Enrich ONLY new place_ids -----------------------
existing_ids = set(places_details["place_id"]) if not places_details.empty else set()
candidate_ids = [pid for pid in places_basic_merged["place_id"].tolist() if pid not in existing_ids]
print("New place_ids to enrich:", len(candidate_ids))

enriched, rev_rows = [], []
for i, pid in enumerate(candidate_ids, start=1):
    try:
        d = place_details_classic(pid)
        if d.get("status") != "OK":  # skip non-OK
            continue
        res = d.get("result", {})
        enriched.append({
            "place_id": pid,
            "name": res.get("name"),
            "lat": (res.get("geometry", {}).get("location", {}) or {}).get("lat"),
            "lng": (res.get("geometry", {}).get("location", {}) or {}).get("lng"),
            "address": res.get("formatted_address"),
            "types": ",".join(res.get("types", [])),
            "rating": res.get("rating"),
            "user_ratings_total": res.get("user_ratings_total"),
            "phone": res.get("international_phone_number"),
            "website": res.get("website"),
            "opening_hours_present": "opening_hours" in res,
            "source_query": "grid",
        })
        for rv in (res.get("reviews") or []):
            rev_rows.append({
                "place_id": pid,
                "author_name": rv.get("author_name"),
                "rating": rv.get("rating"),
                "text": rv.get("text"),
                "time": rv.get("time"),
                "relative_time": rv.get("relative_time_description"),
                "language": rv.get("language"),
            })
    except Exception as e:
        print("details error", pid, "→", e)
    if i % 50 == 0:
        print(f"Details processed: {i}/{len(candidate_ids)}")
    time.sleep(DETAILS_SLEEP)

df_enriched_new = pd.DataFrame(enriched)
df_reviews_new  = pd.DataFrame(rev_rows)

# Infer category for new enriched rows
if not df_enriched_new.empty:
    df_enriched_new["category"] = df_enriched_new["types"].apply(infer_category_from_types)

# Merge with existing details & reviews
if not df_enriched_new.empty:
    places_details_updated = (pd.concat([places_details, df_enriched_new], ignore_index=True)
                              .dropna(subset=["place_id"])
                              .drop_duplicates("place_id")
                              .reset_index(drop=True))
else:
    places_details_updated = places_details.copy()

if not df_reviews_new.empty:
    # make simple review_id if absent
    if "review_id" not in df_reviews_new.columns:
        import hashlib
        df_reviews_new["text"] = df_reviews_new["text"].fillna("")
        df_reviews_new["review_id"] = df_reviews_new.apply(
            lambda r: hashlib.sha256(f"{r.get('place_id','')}|{r.get('time','')}|{r.get('text','')[:32]}".encode("utf-8")).hexdigest()[:24],
            axis=1
        )
    reviews_updated = (pd.concat([reviews, df_reviews_new], ignore_index=True)
                       .dropna(subset=["place_id"])
                       .drop_duplicates(subset=["review_id"] if "review_id" in reviews.columns else None)
                       .reset_index(drop=True))
else:
    reviews_updated = reviews.copy()

# Save updated details & reviews
places_details_updated.to_csv(PLACES_DETAILS_CSV, index=False)
reviews_updated.to_csv(REVIEWS_CSV, index=False)

# ----------------------- Fresh totals -----------------------
after_places_cat  = by_cat_places(places_details_updated)
after_reviews_cat = by_cat_reviews(reviews_updated, places_details_updated)

print("\n=== After grid top-up ===")
print("Places by category:\n", after_places_cat.fillna(0), "\n")
print("Reviews by category:\n", after_reviews_cat.fillna(0), "\n")

delta_places  = (after_places_cat.fillna(0)  - baseline_places_cat.fillna(0)).sort_values(ascending=False)
delta_reviews = (after_reviews_cat.fillna(0) - baseline_reviews_cat.fillna(0)).sort_values(ascending=False)
print("Δ Places by category:\n", delta_places, "\n")
print("Δ Reviews by category:\n", delta_reviews, "\n")

print("Done.")

Grid points: 896 (lat steps=28, lon steps=32)
Est. Nearby calls (no paging): ~4480. With paging up to 4x per center.

=== Baseline (details+reviews) ===
Places by category:
 category
restaurant            96
tourist attraction    77
shopping mall         57
cafe                  24
park                  24
Name: place_id, dtype: int64

Reviews by category:
 category
restaurant            480
tourist attraction    378
shopping mall         276
cafe                  120
park                  119
Name: place_id, dtype: int64

Crawling type: restaurant

HTTPError: 403 Client Error: Forbidden for url: https://places.googleapis.com/v1/places:searchNearby?key=AIzaSyD7HYwB9OeK-Kksk9lXz17y-pwjKOiaNg4

In [81]:
# %pip install requests pandas python-dotenv

import os, time, math, requests, pandas as pd
from pathlib import Path
from dotenv import load_dotenv

# ----------------------- Config -----------------------
load_dotenv()
API_KEY = os.getenv("GOOGLE_API_KEY")
assert API_KEY, "GOOGLE_API_KEY missing. Load your .env first."

# Auckland rough bounds (tweak if desired)
LAT_MIN, LAT_MAX = -37.10, -36.60
LON_MIN, LON_MAX = 174.40, 175.10

# Grid spacing (~km): 0.009 deg lat ≈ 1 km near Auckland
# Start conservative to reduce calls; you can tighten later.
LAT_STEP = 0.027   # ≈ 3 km
LON_STEP = 0.033   # ≈ 3 km
RADIUS_M = 2000    # 2 km radius per grid point

# Place types (classic names)
PLACE_TYPES = ["restaurant","cafe","tourist_attraction","park","shopping_mall"]

# Throttle & paging
NEARBY_SLEEP = 0.40          # between nearby calls
NEARBY_NEXT_TOKEN_SLEEP = 2  # Google requires ~2s before using next_page_token
DETAILS_SLEEP = 0.15         # between details calls
MAX_PAGES_PER_CENTER = 3     # classic nearby has up to 3 pages (~60 results)

# Files
Path("data/processed").mkdir(parents=True, exist_ok=True)
PLACES_BASIC_CSV   = "data/processed/auckland_places_basic.csv"
PLACES_DETAILS_CSV = "data/processed/auckland_places_details.csv"
REVIEWS_CSV        = "data/processed/auckland_reviews.csv"

# ----------------------- Helpers -----------------------
BASE_NEARBY = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
BASE_DETAILS = "https://maps.googleapis.com/maps/api/place/details/json"
DETAIL_FIELDS = (
    "name,place_id,geometry/location,formatted_address,types,"
    "rating,user_ratings_total,international_phone_number,website,opening_hours,"
    "reviews"  # up to 5
)

def nearby_classic(lat, lon, place_type, pagetoken=None):
    params = {
        "key": API_KEY,
        "location": f"{lat},{lon}",
        "radius": RADIUS_M,
        "type": place_type
    }
    if pagetoken:
        params["pagetoken"] = pagetoken
    r = requests.get(BASE_NEARBY, params=params, timeout=30)
    if r.status_code >= 400:
        print("NEARBY ERROR", r.status_code, r.text[:2000])
    r.raise_for_status()
    return r.json()

def crawl_grid_for_type_classic(place_type, centers):
    seen_ids, rows = set(), []
    for (lat, lon) in centers:
        token = None
        for _ in range(MAX_PAGES_PER_CENTER):
            if token:
                time.sleep(NEARBY_NEXT_TOKEN_SLEEP)
            data = nearby_classic(lat, lon, place_type, token)
            for p in data.get("results", []):
                pid = p.get("place_id")
                if pid and pid not in seen_ids:
                    seen_ids.add(pid)
                    loc = (p.get("geometry", {}) or {}).get("location", {}) or {}
                    rows.append({
                        "place_id": pid,
                        "name": p.get("name"),
                        "lat": loc.get("lat"),
                        "lng": loc.get("lng"),
                        "address": p.get("vicinity") or p.get("formatted_address"),
                        "types": ",".join(p.get("types", [])),
                        "source_query": place_type
                    })
            token = data.get("next_page_token")
            if not token:
                break
            time.sleep(NEARBY_SLEEP)
        time.sleep(NEARBY_SLEEP)
    return rows

def place_details_classic(place_id):
    params = {"place_id": place_id, "fields": DETAIL_FIELDS, "key": API_KEY}
    r = requests.get(BASE_DETAILS, params=params, timeout=30)
    if r.status_code >= 400:
        print("DETAILS ERROR", r.status_code, r.text[:2000])
    r.raise_for_status()
    return r.json()

def infer_category_from_types(types_str):
    if pd.isna(types_str): return None
    t = [x.strip().lower() for x in str(types_str).split(",")]
    if "restaurant" in t: return "restaurant"
    if "cafe" in t or "café" in t: return "cafe"
    if "tourist_attraction" in t or "tourist attraction" in t: return "tourist attraction"
    if "park" in t: return "park"
    if "shopping_mall" in t or "shopping mall" in t: return "shopping mall"
    return None

def by_cat_places(df):
    if df.empty: return pd.Series(dtype=int)
    tmp = df.dropna(subset=["place_id"]).drop_duplicates("place_id")
    if "category" not in tmp.columns or tmp["category"].isna().all():
        tmp["category"] = tmp["types"].apply(infer_category_from_types)
    return tmp.groupby("category")["place_id"].nunique().sort_values(ascending=False)

def by_cat_reviews(rev, places_df):
    if rev.empty: return pd.Series(dtype=int)
    tmp = rev.merge(places_df[["place_id","types"]], on="place_id", how="left")
    tmp["category"] = tmp["types"].apply(infer_category_from_types)
    key = "review_id" if "review_id" in tmp.columns else tmp.columns[0]
    return tmp.groupby("category")[key].count().sort_values(ascending=False)

# ----------------------- Build grid -----------------------
lats = []
lat = LAT_MIN
while lat <= LAT_MAX:
    lats.append(round(lat, 6))
    lat += LAT_STEP
lons = []
lon = LON_MIN
while lon <= LON_MAX:
    lons.append(round(lon, 6))
    lon += LON_STEP
centers = [(la, lo) for la in lats for lo in lons]
print(f"Grid points: {len(centers)} (lat steps={len(lats)}, lon steps={len(lons)})")

# ----------------------- Load existing CSVs -----------------------
def load_csv(path, cols=None):
    if not Path(path).exists():
        return pd.DataFrame(columns=cols or [])
    return pd.read_csv(path)

places_basic   = load_csv(PLACES_BASIC_CSV)
places_details = load_csv(PLACES_DETAILS_CSV)
reviews        = load_csv(REVIEWS_CSV)

print("\n=== Baseline (details+reviews) ===")
print("Places by category:\n", by_cat_places(places_details).fillna(0), "\n")
print("Reviews by category:\n", by_cat_reviews(reviews, places_details).fillna(0), "\n")

# ----------------------- Crawl grid by classic nearby -----------------------
all_rows = []
for t in PLACE_TYPES:
    print("Crawling type:", t)
    rows = crawl_grid_for_type_classic(t, centers)
    all_rows.extend(rows)
    print(f"  Collected {len(rows)} rows for {t}")

df_grid = (pd.DataFrame(all_rows)
           .dropna(subset=["place_id"])
           .drop_duplicates("place_id")
           .reset_index(drop=True))
print("Unique places from grid:", df_grid["place_id"].nunique())

# Merge with existing basic and save
if not places_basic.empty:
    places_basic_merged = (pd.concat([places_basic, df_grid], ignore_index=True)
                           .dropna(subset=["place_id"])
                           .drop_duplicates("place_id")
                           .reset_index(drop=True))
else:
    places_basic_merged = df_grid.copy()
places_basic_merged.to_csv(PLACES_BASIC_CSV, index=False)
print("Saved merged basic list →", PLACES_BASIC_CSV)

# ----------------------- Enrich ONLY new place_ids -----------------------
existing_ids = set(places_details["place_id"]) if not places_details.empty else set()
candidate_ids = [pid for pid in places_basic_merged["place_id"].tolist() if pid not in existing_ids]
print("New place_ids to enrich:", len(candidate_ids))

enriched, rev_rows = [], []
for i, pid in enumerate(candidate_ids, start=1):
    try:
        d = place_details_classic(pid)
        if d.get("status") != "OK":
            continue
        res = d.get("result", {})
        enriched.append({
            "place_id": pid,
            "name": res.get("name"),
            "lat": (res.get("geometry", {}).get("location", {}) or {}).get("lat"),
            "lng": (res.get("geometry", {}).get("location", {}) or {}).get("lng"),
            "address": res.get("formatted_address"),
            "types": ",".join(res.get("types", [])),
            "rating": res.get("rating"),
            "user_ratings_total": res.get("user_ratings_total"),
            "phone": res.get("international_phone_number"),
            "website": res.get("website"),
            "opening_hours_present": "opening_hours" in res,
            "source_query": "grid_classic",
        })
        for rv in (res.get("reviews") or []):
            rev_rows.append({
                "place_id": pid,
                "author_name": rv.get("author_name"),
                "rating": rv.get("rating"),
                "text": rv.get("text"),
                "time": rv.get("time"),
                "relative_time": rv.get("relative_time_description"),
                "language": rv.get("language"),
            })
    except Exception as e:
        print("details error", pid, "→", e)
    if i % 50 == 0:
        print(f"Details processed: {i}/{len(candidate_ids)}")
    time.sleep(DETAILS_SLEEP)

df_enriched_new = pd.DataFrame(enriched)
df_reviews_new  = pd.DataFrame(rev_rows)

# Add simple categories for new rows
if not df_enriched_new.empty:
    df_enriched_new["category"] = df_enriched_new["types"].apply(infer_category_from_types)

# Merge & save
if not df_enriched_new.empty:
    places_details_updated = (pd.concat([places_details, df_enriched_new], ignore_index=True)
                              .dropna(subset=["place_id"])
                              .drop_duplicates("place_id")
                              .reset_index(drop=True))
else:
    places_details_updated = places_details.copy()
if not df_reviews_new.empty:
    if "review_id" not in df_reviews_new.columns:
        import hashlib
        df_reviews_new["text"] = df_reviews_new["text"].fillna("")
        df_reviews_new["review_id"] = df_reviews_new.apply(
            lambda r: hashlib.sha256(f"{r.get('place_id','')}|{r.get('time','')}|{r.get('text','')[:32]}".encode("utf-8")).hexdigest()[:24],
            axis=1
        )
    reviews_updated = (pd.concat([reviews, df_reviews_new], ignore_index=True)
                       .dropna(subset=["place_id"])
                       .drop_duplicates(subset=["review_id"] if "review_id" in reviews.columns else None)
                       .reset_index(drop=True))
else:
    reviews_updated = reviews.copy()

places_details_updated.to_csv(PLACES_DETAILS_CSV, index=False)
reviews_updated.to_csv(REVIEWS_CSV, index=False)

# ----------------------- Fresh totals -----------------------
print("\n=== After grid top-up (classic nearby) ===")
print("Places by category:\n", by_cat_places(places_details_updated).fillna(0), "\n")
print("Reviews by category:\n", by_cat_reviews(reviews_updated, places_details_updated).fillna(0), "\n")

print("Done.")

Grid points: 418 (lat steps=19, lon steps=22)

=== Baseline (details+reviews) ===
Places by category:
 category
restaurant            96
tourist attraction    77
shopping mall         57
cafe                  24
park                  24
Name: place_id, dtype: int64

Reviews by category:
 category
restaurant            480
tourist attraction    378
shopping mall         276
cafe                  120
park                  119
Name: place_id, dtype: int64

Crawling type: restaurant

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

In [83]:
# --- Patch: robust nearby + details crawl with progress, backoff, checkpoints, resume ---

import os, time, json, hashlib, pandas as pd
from pathlib import Path

CHECKPOINT_DIR = Path("data/checkpoints")
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

NEARBY_MAX_RETRIES = 6
DETAILS_MAX_RETRIES = 4

def _nearby_with_backoff(lat, lon, place_type, pagetoken=None):
    """Classic Nearby Search with exponential backoff on OVER_QUERY_LIMIT / 5xx."""
    backoff = 1.0
    for attempt in range(1, NEARBY_MAX_RETRIES + 1):
        data = nearby_classic(lat, lon, place_type, pagetoken)
        status = data.get("status", "OK")
        if status in ("OK", "ZERO_RESULTS"):
            return data
        if status in ("OVER_QUERY_LIMIT", "UNKNOWN_ERROR"):
            time.sleep(backoff)
            backoff = min(backoff * 1.7, 15.0)
            continue
        # Other statuses (REQUEST_DENIED, INVALID_REQUEST) – print and return as-is
        print(f"NEARBY status={status} lat={lat}, lon={lon}, type={place_type}, token={bool(pagetoken)}")
        return data
    # After retries, return last data (may be non-OK)
    return data

def _details_with_backoff(place_id):
    """Place Details with exponential backoff on 5xx / over-limit."""
    backoff = 1.0
    for attempt in range(1, DETAILS_MAX_RETRIES + 1):
        d = place_details_classic(place_id)
        status = d.get("status", "OK")
        if status == "OK":
            return d
        if status in ("OVER_QUERY_LIMIT", "UNKNOWN_ERROR"):
            time.sleep(backoff)
            backoff = min(backoff * 1.7, 15.0)
            continue
        print(f"DETAILS status={status} place_id={place_id}")
        return d
    return d

def _checkpoint_paths(tag):
    return (
        CHECKPOINT_DIR / f"nearby_rows_{tag}.csv",
        CHECKPOINT_DIR / f"state_{tag}.json",
        CHECKPOINT_DIR / f"details_rows_{tag}.csv",
    )

def save_state(tag, seen_ids, center_index):
    _, state_path, _ = _checkpoint_paths(tag)
    with open(state_path, "w", encoding="utf-8") as f:
        json.dump({"center_index": center_index, "seen_ids": list(seen_ids)}, f)

def load_state(tag):
    _, state_path, _ = _checkpoint_paths(tag)
    if state_path.exists():
        with open(state_path, "r", encoding="utf-8") as f:
            obj = json.load(f)
        return set(obj.get("seen_ids", [])), int(obj.get("center_index", 0))
    return set(), 0

def append_csv(path, rows, columns):
    df = pd.DataFrame(rows, columns=columns) if rows else pd.DataFrame(columns=columns)
    if path.exists():
        df.to_csv(path, mode="a", header=False, index=False)
    else:
        df.to_csv(path, index=False)

def crawl_grid_for_type_classic_checkpointed(place_type, centers, checkpoint_every=30, resume=True):
    """
    Crawl classic Nearby over centers for one type with:
      - progress prints
      - exponential backoff
      - checkpointing every N centers
      - resume support
    Returns a DataFrame of unique places (deduped by place_id).
    """
    rows_cols = ["place_id","name","lat","lng","address","types","source_query"]
    near_path, state_path, _ = _checkpoint_paths(place_type)

    seen_ids, start_idx = load_state(place_type) if resume else (set(), 0)
    collected_rows = []
    last_flush_idx = start_idx

    print(f"[{place_type}] Resume from center #{start_idx} (seen_ids={len(seen_ids)})")

    for ci in range(start_idx, len(centers)):
        lat, lon = centers[ci]
        token = None
        for _ in range(MAX_PAGES_PER_CENTER):
            if token:
                time.sleep(NEARBY_NEXT_TOKEN_SLEEP)
            data = _nearby_with_backoff(lat, lon, place_type, token)
            status = data.get("status", "OK")
            if status not in ("OK", "ZERO_RESULTS"):
                # still store partial rows if any, then break
                for p in data.get("results", []):
                    pid = p.get("place_id")
                    if pid and pid not in seen_ids:
                        seen_ids.add(pid)
                        loc = (p.get("geometry", {}) or {}).get("location", {}) or {}
                        collected_rows.append([
                            pid, p.get("name"), loc.get("lat"), loc.get("lng"),
                            p.get("vicinity") or p.get("formatted_address"),
                            ",".join(p.get("types", [])), place_type
                        ])
                break
            for p in data.get("results", []):
                pid = p.get("place_id")
                if pid and pid not in seen_ids:
                    seen_ids.add(pid)
                    loc = (p.get("geometry", {}) or {}).get("location", {}) or {}
                    collected_rows.append([
                        pid, p.get("name"), loc.get("lat"), loc.get("lng"),
                        p.get("vicinity") or p.get("formatted_address"),
                        ",".join(p.get("types", [])), place_type
                    ])
            token = data.get("next_page_token")
            if not token:
                break

        # checkpoint every N centers
        if (ci - last_flush_idx + 1) >= checkpoint_every:
            if collected_rows:
                append_csv(near_path, collected_rows, rows_cols)
                collected_rows = []
            save_state(place_type, seen_ids, ci + 1)  # next start index
            print(f"[{place_type}] checkpoint at center #{ci+1} | seen_ids={len(seen_ids)} | saved to {near_path}")
            last_flush_idx = ci + 1
        time.sleep(NEARBY_SLEEP)

    # flush remainder
    if collected_rows:
        append_csv(near_path, collected_rows, rows_cols)
    save_state(place_type, seen_ids, len(centers))
    print(f"[{place_type}] finished crawl | total seen_ids={len(seen_ids)} | checkpoints in {CHECKPOINT_DIR}")

    # Load all nearby rows for this type (across checkpoints) and dedupe
    df_all = pd.read_csv(near_path) if near_path.exists() else pd.DataFrame(columns=rows_cols)
    df_all = df_all.dropna(subset=["place_id"]).drop_duplicates("place_id").reset_index(drop=True)
    return df_all

def enrich_only_new_with_checkpoint(new_place_ids, tag="grid_classic", chunk=100):
    """
    Enrich only new place_ids with Place Details (classic).
    Saves partial details & reviews to checkpoint CSVs every 'chunk' places.
    """
    _, _, details_path = _checkpoint_paths(tag)
    details_cols = ["place_id","name","lat","lng","address","types","rating","user_ratings_total","phone","website","opening_hours_present","source_query"]
    reviews_cols = ["place_id","author_name","rating","text","time","relative_time","language","review_id"]

    details_buffer, reviews_buffer = [], []
    total = len(new_place_ids)
    for i, pid in enumerate(new_place_ids, 1):
        d = _details_with_backoff(pid)
        if d.get("status") == "OK":
            res = d.get("result", {})
            details_buffer.append([
                pid,
                res.get("name"),
                (res.get("geometry", {}).get("location", {}) or {}).get("lat"),
                (res.get("geometry", {}).get("location", {}) or {}).get("lng"),
                res.get("formatted_address"),
                ",".join(res.get("types", [])),
                res.get("rating"),
                res.get("user_ratings_total"),
                res.get("international_phone_number"),
                res.get("website"),
                "opening_hours" in res,
                tag
            ])
            # reviews (up to 5)
            for rv in (res.get("reviews") or []):
                text = (rv.get("text") or "")
                rid = hashlib.sha256(f"{pid}|{rv.get('time')}|{text[:32]}".encode("utf-8")).hexdigest()[:24]
                reviews_buffer.append([
                    pid, rv.get("author_name"), rv.get("rating"), text,
                    rv.get("time"), rv.get("relative_time_description"),
                    rv.get("language"), rid
                ])
        # checkpoint every 'chunk'
        if i % chunk == 0:
            if details_buffer:
                append_csv(CHECKPOINT_DIR / f"details_{tag}.csv", details_buffer, details_cols)
                details_buffer = []
            if reviews_buffer:
                append_csv(CHECKPOINT_DIR / f"reviews_{tag}.csv", reviews_buffer, reviews_cols)
                reviews_buffer = []
            print(f"[details] {i}/{total} enriched and checkpointed")
        time.sleep(DETAILS_SLEEP)

    # flush remainder
    if details_buffer:
        append_csv(CHECKPOINT_DIR / f"details_{tag}.csv", details_buffer, details_cols)
    if reviews_buffer:
        append_csv(CHECKPOINT_DIR / f"reviews_{tag}.csv", reviews_buffer, reviews_cols)
    print("[details] enrichment finished and checkpointed")

In [85]:
# Crawl (resume-safe)
df_rest = crawl_grid_for_type_classic_checkpointed("restaurant", centers, checkpoint_every=30, resume=True)
print("Unique restaurants (this run):", df_rest["place_id"].nunique())

# Merge into your basic CSV
import pandas as pd
from pathlib import Path

PLACES_BASIC_CSV   = "data/processed/auckland_places_basic.csv"
PLACES_DETAILS_CSV = "data/processed/auckland_places_details.csv"
REVIEWS_CSV        = "data/processed/auckland_reviews.csv"

places_basic = pd.read_csv(PLACES_BASIC_CSV) if Path(PLACES_BASIC_CSV).exists() else pd.DataFrame()
df_basic_merged = (pd.concat([places_basic, df_rest], ignore_index=True)
                   .dropna(subset=["place_id"])
                   .drop_duplicates("place_id")
                   .reset_index(drop=True))
df_basic_merged.to_csv(PLACES_BASIC_CSV, index=False)

# Enrich only NEW place_ids
places_details_existing = pd.read_csv(PLACES_DETAILS_CSV) if Path(PLACES_DETAILS_CSV).exists() else pd.DataFrame()
existing_ids = set(places_details_existing["place_id"]) if not places_details_existing.empty else set()
new_ids = [pid for pid in df_basic_merged["place_id"].tolist() if pid not in existing_ids]
print("New place_ids to enrich (restaurants):", len(new_ids))

# Enrich with checkpoints (safe to stop/restart)
enrich_only_new_with_checkpoint(new_ids, tag="grid_classic_restaurant", chunk=100)

# Combine checkpointed results back into your main CSVs
def combine_back_into_main(tag):
    import pandas as pd
    from pathlib import Path
    CKPT = Path("data/checkpoints")
    det_ckpt = CKPT / f"details_{tag}.csv"
    rev_ckpt = CKPT / f"reviews_{tag}.csv"

    if det_ckpt.exists():
        df_new_det = pd.read_csv(det_ckpt)
        if "category" not in df_new_det.columns:
            df_new_det["category"] = df_new_det["types"].apply(infer_category_from_types)
        if Path(PLACES_DETAILS_CSV).exists():
            df_det_old = pd.read_csv(PLACES_DETAILS_CSV)
            df_det_all = (pd.concat([df_det_old, df_new_det], ignore_index=True)
                          .dropna(subset=["place_id"]).drop_duplicates("place_id").reset_index(drop=True))
        else:
            df_det_all = df_new_det
        df_det_all.to_csv(PLACES_DETAILS_CSV, index=False)

    if rev_ckpt.exists():
        df_new_rev = pd.read_csv(rev_ckpt)
        if "review_id" not in df_new_rev.columns:
            import hashlib
            df_new_rev["text"] = df_new_rev["text"].fillna("")
            df_new_rev["review_id"] = df_new_rev.apply(
                lambda r: hashlib.sha256(f"{r.get('place_id','')}|{r.get('time','')}|{r.get('text','')[:32]}".encode("utf-8")).hexdigest()[:24],
                axis=1
            )
        if Path(REVIEWS_CSV).exists():
            df_rev_old = pd.read_csv(REVIEWS_CSV)
            df_rev_all = (pd.concat([df_rev_old, df_new_rev], ignore_index=True)
                          .dropna(subset=["place_id"])
                          .drop_duplicates(subset=["review_id"])
                          .reset_index(drop=True))
        else:
            df_rev_all = df_new_rev
        df_rev_all.to_csv(REVIEWS_CSV, index=False)

combine_back_into_main("grid_classic_restaurant")

# Fresh totals
places_details_updated = pd.read_csv(PLACES_DETAILS_CSV) if Path(PLACES_DETAILS_CSV).exists() else pd.DataFrame()
reviews_updated = pd.read_csv(REVIEWS_CSV) if Path(REVIEWS_CSV).exists() else pd.DataFrame()
print("\n=== Totals after restaurants run ===")
print("Places by category:\n", by_cat_places(places_details_updated).fillna(0), "\n")
print("Reviews by category:\n", by_cat_reviews(reviews_updated, places_details_updated).fillna(0), "\n")

[restaurant] Resume from center #0 (seen_ids=0)
[restaurant] checkpoint at center #30 | seen_ids=13 | saved to data\checkpoints\nearby_rows_restaurant.csv
[restaurant] checkpoint at center #60 | seen_ids=153 | saved to data\checkpoints\nearby_rows_restaurant.csv
[restaurant] checkpoint at center #90 | seen_ids=322 | saved to data\checkpoints\nearby_rows_restaurant.csv
[restaurant] checkpoint at center #120 | seen_ids=478 | saved to data\checkpoints\nearby_rows_restaurant.csv
[restaurant] checkpoint at center #150 | seen_ids=1037 | saved to data\checkpoints\nearby_rows_restaurant.csv
[restaurant] checkpoint at center #180 | seen_ids=1525 | saved to data\checkpoints\nearby_rows_restaurant.csv
[restaurant] checkpoint at center #210 | seen_ids=2232 | saved to data\checkpoints\nearby_rows_restaurant.csv
[restaurant] checkpoint at center #240 | seen_ids=2569 | saved to data\checkpoints\nearby_rows_restaurant.csv
[restaurant] checkpoint at center #270 | seen_ids=2854 | saved to data\checkpoints\nearby_rows_restaurant.csv
[restaurant] checkpoint at center #300 | seen_ids=3118 | saved to data\checkpoints\nearby_rows_restaurant.csv
[restaurant] checkpoint at center #330 | seen_ids=3272 | saved to data\checkpoints\nearby_rows_restaurant.csv
[restaurant] checkpoint at center #360 | seen_ids=3311 | saved to data\checkpoints\nearby_rows_restaurant.csv
[restaurant] checkpoint at center #390 | seen_ids=3363 | saved to data\checkpoints\nearby_rows_restaurant.csv
[restaurant] finished crawl | total seen_ids=3438 | checkpoints in data\checkpoints
Unique restaurants (this run): 3438
New place_ids to enrich (restaurants): 3389
[details] 100/3389 enriched and checkpointed
[details] 200/3389 enriched and checkpointed

PermissionError: [Errno 13] Permission denied: 'data\\checkpoints\\reviews_grid_classic_restaurant.csv'

In [87]:
from pathlib import Path
import pandas as pd

PLACES_BASIC_CSV   = "data/processed/auckland_places_basic.csv"
PLACES_DETAILS_CSV = "data/processed/auckland_places_details.csv"

# Read the current basic + details
df_basic = pd.read_csv(PLACES_BASIC_CSV)
df_details = pd.read_csv(PLACES_DETAILS_CSV) if Path(PLACES_DETAILS_CSV).exists() else pd.DataFrame()

# New IDs you computed earlier:
existing_ids = set(df_details["place_id"]) if not df_details.empty else set()
new_ids = [pid for pid in df_basic["place_id"].tolist() if pid not in existing_ids]

# Skip IDs already checkpointed in details (progress you’ve saved)
det_ckpt = Path("data/checkpoints/details_grid_classic_restaurant.csv")
done_ids = set(pd.read_csv(det_ckpt, usecols=["place_id"])["place_id"]) if det_ckpt.exists() else set()

remaining_ids = [pid for pid in new_ids if pid not in done_ids]
print("Remaining to enrich (restaurants):", len(remaining_ids))

# Re-run enrichment on the remaining only
enrich_only_new_with_checkpoint(remaining_ids, tag="grid_classic_restaurant", chunk=100)

Remaining to enrich (restaurants): 3089
[details] 100/3089 enriched and checkpointed
[details] 200/3089 enriched and checkpointed
[details] 300/3089 enriched and checkpointed
[details] 400/3089 enriched and checkpointed

SSLError: HTTPSConnectionPool(host='maps.googleapis.com', port=443): Max retries exceeded with url: /maps/api/place/details/json?place_id=ChIJVbus5xRDDW0Rj1HKa6RXDaQ&fields=name%2Cplace_id%2Cgeometry%2Flocation%2Cformatted_address%2Ctypes%2Crating%2Cuser_ratings_total%2Cinternational_phone_number%2Cwebsite%2Copening_hours%2Creviews&key=AIzaSyD7HYwB9OeK-Kksk9lXz17y-pwjKOiaNg4 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))

In [89]:
%pip install --upgrade requests urllib3 certifi idna

Requirement already satisfied: requests in c:\users\arjun\anaconda3\lib\site-packages (2.32.2)Note: you may need to restart the kernel to use updated packages.

Collecting requests
  Downloading requests-2.32.4-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: urllib3 in c:\users\arjun\anaconda3\lib\site-packages (2.2.2)
Collecting urllib3
  Downloading urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: certifi in c:\users\arjun\anaconda3\lib\site-packages (2024.7.4)
Collecting certifi
  Downloading certifi-2025.8.3-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: idna in c:\users\arjun\anaconda3\lib\site-packages (3.7)
Collecting idna
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\arjun\anaconda3\lib\site-packages (from requests) (2.0.4)
Downloading requests-2.32.4-py3-none-any.whl (64 kB)
   ---------------------------------------- 0.0/64.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/64.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/64.8 kB ? eta -:--:--
   ------------------------- -------------- 41.0/64.8 kB 991.0 kB/s eta 0:00:01
   ------------------------- -------------- 41.0/64.8 kB 991.0 kB/s eta 0:00:01
   ---------------------------------------- 64.8/64.8 kB 501.0 kB/s eta 0:00:00
Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
   ---------------------------------------- 0.0/129.8 kB ? eta -:--:--
   ------------------------------- -------- 102.4/129.8 kB 5.8 MB/s eta 0:00:01
   ---------------------------------------- 129.8/129.8 kB 1.9 MB/s eta 0:00:00
Downloading certifi-2025.8.3-py3-none-any.whl (161 kB)
   ---------------------------------------- 0.0/161.2 kB ? eta -:--:--
   ---------------------------------------- 161.2/161.2 kB 4.9 MB/s eta 0:00:00
Downloading idna-3.10-py3-none-any.whl (70 kB)
   ---------------------------------------- 0.0/70.4 kB ? eta -:--:--
   ---------------------------------------- 70.4/70.4 kB 4.0 MB/s eta 0:00:00
Installing collected packages: urllib3, idna, certifi, requests
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.2.2
    Uninstalling urllib3-2.2.2:
      Successfully uninstalled urllib3-2.2.2
  Attempting uninstall: idna
    Found existing installation: idna 3.7
    Uninstalling idna-3.7:
      Successfully uninstalled idna-3.7
  Attempting uninstall: certifi
    Found existing installation: certifi 2024.7.4
    Uninstalling certifi-2024.7.4:
      Successfully uninstalled certifi-2024.7.4
  Attempting uninstall: requests
    Found existing installation: requests 2.32.2
    Uninstalling requests-2.32.2:
      Successfully uninstalled requests-2.32.2
Successfully installed certifi-2025.8.3 idna-3.10 requests-2.32.4 urllib3-2.5.0

In [91]:
import requests, time, random
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# Global Session with connection pooling + retry on transient errors
SESSION = requests.Session()
retries = Retry(
    total=7, connect=7, read=7,
    backoff_factor=1.3,  # exponential backoff
    status_forcelist=[429, 500, 502, 503, 504],
    allowed_methods={"GET", "POST"},
    raise_on_status=False,
)
adapter = HTTPAdapter(max_retries=retries, pool_connections=50, pool_maxsize=50)
SESSION.mount("https://", adapter)
SESSION.mount("http://", adapter)

BASE_DETAILS = "https://maps.googleapis.com/maps/api/place/details/json"
DETAIL_FIELDS = (
    "name,place_id,geometry/location,formatted_address,types,"
    "rating,user_ratings_total,international_phone_number,website,opening_hours,reviews"
)

def place_details_classic(place_id):
    """Use the global SESSION for resilient calls."""
    params = {"place_id": place_id, "fields": DETAIL_FIELDS, "key": API_KEY}
    # timeout tuple: (connect timeout, read timeout)
    return SESSION.get(BASE_DETAILS, params=params, timeout=(10, 30)).json()

def _details_with_backoff(place_id):
    """Retry on Google status AND on network/SSL errors."""
    backoff = 1.0
    for attempt in range(1, 9):  # up to 8 tries
        try:
            d = place_details_classic(place_id)
        except (requests.exceptions.SSLError,
                requests.exceptions.ConnectionError,
                requests.exceptions.ReadTimeout,
                requests.exceptions.ChunkedEncodingError) as e:
            # Transport-level error: wait and retry
            wait = backoff + random.uniform(0, 0.5)
            print(f"NET/SSL error on details {place_id} (attempt {attempt}): {e.__class__.__name__}; sleeping {wait:.1f}s")
            time.sleep(wait)
            backoff = min(backoff * 1.7, 20.0)
            continue

        status = d.get("status", "OK")
        if status == "OK":
            return d
        if status in ("OVER_QUERY_LIMIT", "UNKNOWN_ERROR"):
            wait = backoff + random.uniform(0, 0.5)
            print(f"Google status {status} for {place_id} (attempt {attempt}); sleeping {wait:.1f}s")
            time.sleep(wait)
            backoff = min(backoff * 1.7, 20.0)
            continue

        # REQUEST_DENIED, INVALID_REQUEST, NOT_FOUND, etc. → skip gracefully
        if status and status != "OK":
            print(f"Skip {place_id}: Google status {status}")
            return d

    # Give up after retries (caller will just not add this place's reviews)
    return {"status": "SKIPPED"}

In [93]:
from pathlib import Path
import pandas as pd

PLACES_BASIC_CSV   = "data/processed/auckland_places_basic.csv"
PLACES_DETAILS_CSV = "data/processed/auckland_places_details.csv"

df_basic   = pd.read_csv(PLACES_BASIC_CSV)
df_details = pd.read_csv(PLACES_DETAILS_CSV) if Path(PLACES_DETAILS_CSV).exists() else pd.DataFrame()

existing_ids = set(df_details["place_id"]) if not df_details.empty else set()
new_ids_all  = [pid for pid in df_basic["place_id"].tolist() if pid not in existing_ids]

det_ckpt = Path("data/checkpoints/details_grid_classic_restaurant.csv")
done_ids = set(pd.read_csv(det_ckpt, usecols=["place_id"])["place_id"]) if det_ckpt.exists() else set()

remaining_ids = [pid for pid in new_ids_all if pid not in done_ids]
print("Remaining to enrich (restaurants):", len(remaining_ids))

enrich_only_new_with_checkpoint(remaining_ids, tag="grid_classic_restaurant", chunk=100)

Remaining to enrich (restaurants): 2689
[details] 100/2689 enriched and checkpointed
[details] 200/2689 enriched and checkpointed
[details] 300/2689 enriched and checkpointed
[details] 400/2689 enriched and checkpointed
[details] 500/2689 enriched and checkpointed
[details] 600/2689 enriched and checkpointed
[details] 700/2689 enriched and checkpointed
[details] 800/2689 enriched and checkpointed
[details] 900/2689 enriched and checkpointed
[details] 1000/2689 enriched and checkpointed
[details] 1100/2689 enriched and checkpointed
[details] 1200/2689 enriched and checkpointed
[details] 1300/2689 enriched and checkpointed
[details] 1400/2689 enriched and checkpointed
[details] 1500/2689 enriched and checkpointed
[details] 1600/2689 enriched and checkpointed
[details] 1700/2689 enriched and checkpointed
[details] 1800/2689 enriched and checkpointed
[details] 1900/2689 enriched and checkpointed
[details] 2000/2689 enriched and checkpointed
[details] 2100/2689 enriched and checkpointed
[details] 2200/2689 enriched and checkpointed
[details] 2300/2689 enriched and checkpointed
[details] 2400/2689 enriched and checkpointed
[details] 2500/2689 enriched and checkpointed
[details] 2600/2689 enriched and checkpointed
[details] enrichment finished and checkpointed

In [95]:
# ==== SET THESE TWO AND RUN ====
CURRENT_TYPE = "tourist_attraction"      # then "park", then "shopping_mall"
TAG          = "grid_classic_tourist_attraction"  # then "grid_classic_park", "grid_classic_shopping_mall"

# 1) Crawl grid (resume-safe, checkpointed)
df_type = crawl_grid_for_type_classic_checkpointed(CURRENT_TYPE, centers, checkpoint_every=30, resume=True)
print(f"Unique {CURRENT_TYPE} discovered this run:", df_type["place_id"].nunique())

# 2) Merge into basic list
import pandas as pd
from pathlib import Path

PLACES_BASIC_CSV   = "data/processed/auckland_places_basic.csv"
PLACES_DETAILS_CSV = "data/processed/auckland_places_details.csv"
REVIEWS_CSV        = "data/processed/auckland_reviews.csv"

places_basic = pd.read_csv(PLACES_BASIC_CSV) if Path(PLACES_BASIC_CSV).exists() else pd.DataFrame()
df_basic_merged = (pd.concat([places_basic, df_type], ignore_index=True)
                   .dropna(subset=["place_id"])
                   .drop_duplicates("place_id")
                   .reset_index(drop=True))
df_basic_merged.to_csv(PLACES_BASIC_CSV, index=False)

# 3) Enrich ONLY new place_ids (resume-safe)
places_details_existing = pd.read_csv(PLACES_DETAILS_CSV) if Path(PLACES_DETAILS_CSV).exists() else pd.DataFrame()
existing_ids = set(places_details_existing["place_id"]) if not places_details_existing.empty else set()
new_ids = [pid for pid in df_basic_merged["place_id"].tolist() if pid not in existing_ids]

# Skip IDs already checkpointed for this TAG
from pathlib import Path
det_ckpt = Path(f"data/checkpoints/details_{TAG}.csv")
done_ids = set(pd.read_csv(det_ckpt, usecols=["place_id"])["place_id"]) if det_ckpt.exists() else set()

remaining_ids = [pid for pid in new_ids if pid not in done_ids]
print(f"Remaining to enrich ({CURRENT_TYPE}):", len(remaining_ids))

enrich_only_new_with_checkpoint(remaining_ids, tag=TAG, chunk=100)

# 4) Combine checkpoint results back into main CSVs
def infer_category_priority(types_str):
    """Map Google's many types into your 5 buckets with a clear priority."""
    if pd.isna(types_str): return None
    t = {x.strip().lower() for x in str(types_str).split(",")}
    # priority: malls > tourist attractions > parks > restaurants > cafes
    if "shopping_mall" in t or "shopping mall" in t: return "shopping mall"
    if "tourist_attraction" in t or "tourist attraction" in t: return "tourist attraction"
    if "park" in t: return "park"
    if {"restaurant","meal_takeaway","meal_delivery","fast_food"} & t: return "restaurant"
    if {"cafe","coffee_shop","café"} & t: return "cafe"
    return None

def combine_back_into_main(tag):
    import pandas as pd
    from pathlib import Path
    CKPT = Path("data/checkpoints")

    det_ckpt = CKPT / f"details_{tag}.csv"
    if det_ckpt.exists():
        df_new_det = pd.read_csv(det_ckpt)
        # normalize category
        df_new_det["category"] = df_new_det["types"].apply(infer_category_priority)
        if Path(PLACES_DETAILS_CSV).exists():
            df_det_old = pd.read_csv(PLACES_DETAILS_CSV)
            df_det_all = (pd.concat([df_det_old, df_new_det], ignore_index=True)
                          .dropna(subset=["place_id"])
                          .drop_duplicates("place_id")
                          .reset_index(drop=True))
        else:
            df_det_all = df_new_det
        df_det_all.to_csv(PLACES_DETAILS_CSV, index=False)

    rev_ckpt = CKPT / f"reviews_{tag}.csv"
    if rev_ckpt.exists():
        df_new_rev = pd.read_csv(rev_ckpt)
        if "review_id" not in df_new_rev.columns:
            import hashlib
            df_new_rev["text"] = df_new_rev["text"].fillna("")
            df_new_rev["review_id"] = df_new_rev.apply(
                lambda r: hashlib.sha256(f"{r.get('place_id','')}|{r.get('time','')}|{r.get('text','')[:32]}".encode("utf-8")).hexdigest()[:24],
                axis=1
            )
        if Path(REVIEWS_CSV).exists():
            df_rev_old = pd.read_csv(REVIEWS_CSV)
            df_rev_all = (pd.concat([df_rev_old, df_new_rev], ignore_index=True)
                          .dropna(subset=["place_id"])
                          .drop_duplicates(subset=["review_id"])
                          .reset_index(drop=True))
        else:
            df_rev_all = df_new_rev
        df_rev_all.to_csv(REVIEWS_CSV, index=False)

combine_back_into_main(TAG)

# 5) Print fresh totals
def by_cat_places(df):
    if df.empty: return pd.Series(dtype=int)
    tmp = df.dropna(subset=["place_id"]).drop_duplicates("place_id")
    if "category" not in tmp.columns or tmp["category"].isna().all():
        tmp["category"] = tmp["types"].apply(infer_category_priority)
    return tmp.groupby("category")["place_id"].nunique().sort_values(ascending=False)

def by_cat_reviews(rev, places_df):
    if rev.empty: return pd.Series(dtype=int)
    tmp = rev.merge(places_df[["place_id","types","category"]], on="place_id", how="left")
    if "category" not in tmp.columns or tmp["category"].isna().all():
        tmp["category"] = tmp["types"].apply(infer_category_priority)
    key = "review_id" if "review_id" in tmp.columns else tmp.columns[0]
    return tmp.groupby("category")[key].count().sort_values(ascending=False)

places_details_updated = pd.read_csv(PLACES_DETAILS_CSV) if Path(PLACES_DETAILS_CSV).exists() else pd.DataFrame()
reviews_updated       = pd.read_csv(REVIEWS_CSV)        if Path(REVIEWS_CSV).exists() else pd.DataFrame()

print("\n=== Totals after this type ===")
print("Places by category:\n", by_cat_places(places_details_updated).fillna(0), "\n")
print("Reviews by category:\n", by_cat_reviews(reviews_updated, places_details_updated).fillna(0), "\n")

[tourist_attraction] Resume from center #0 (seen_ids=0)
[tourist_attraction] checkpoint at center #30 | seen_ids=2 | saved to data\checkpoints\nearby_rows_tourist_attraction.csv
[tourist_attraction] checkpoint at center #60 | seen_ids=17 | saved to data\checkpoints\nearby_rows_tourist_attraction.csv
[tourist_attraction] checkpoint at center #90 | seen_ids=27 | saved to data\checkpoints\nearby_rows_tourist_attraction.csv
[tourist_attraction] checkpoint at center #120 | seen_ids=69 | saved to data\checkpoints\nearby_rows_tourist_attraction.csv
[tourist_attraction] checkpoint at center #150 | seen_ids=118 | saved to data\checkpoints\nearby_rows_tourist_attraction.csv
[tourist_attraction] checkpoint at center #180 | seen_ids=171 | saved to data\checkpoints\nearby_rows_tourist_attraction.csv
[tourist_attraction] checkpoint at center #210 | seen_ids=319 | saved to data\checkpoints\nearby_rows_tourist_attraction.csv
[tourist_attraction] checkpoint at center #240 | seen_ids=414 | saved to data\checkpoints\nearby_rows_tourist_attraction.csv
[tourist_attraction] checkpoint at center #270 | seen_ids=453 | saved to data\checkpoints\nearby_rows_tourist_attraction.csv
[tourist_attraction] checkpoint at center #300 | seen_ids=488 | saved to data\checkpoints\nearby_rows_tourist_attraction.csv
[tourist_attraction] checkpoint at center #330 | seen_ids=505 | saved to data\checkpoints\nearby_rows_tourist_attraction.csv
[tourist_attraction] checkpoint at center #360 | seen_ids=513 | saved to data\checkpoints\nearby_rows_tourist_attraction.csv
[tourist_attraction] checkpoint at center #390 | seen_ids=520 | saved to data\checkpoints\nearby_rows_tourist_attraction.csv
[tourist_attraction] finished crawl | total seen_ids=541 | checkpoints in data\checkpoints
Unique tourist_attraction discovered this run: 541
Remaining to enrich (tourist_attraction): 3846
[details] 100/3846 enriched and checkpointed
[details] 200/3846 enriched and checkpointed
[details] 300/3846 enriched and checkpointed
[details] 400/3846 enriched and checkpointed
[details] 500/3846 enriched and checkpointed
[details] 600/3846 enriched and checkpointed
[details] 700/3846 enriched and checkpointed
[details] 800/3846 enriched and checkpointed
[details] 900/3846 enriched and checkpointed
[details] 1000/3846 enriched and checkpointed
[details] 1100/3846 enriched and checkpointed
[details] 1200/3846 enriched and checkpointed
[details] 1300/3846 enriched and checkpointed
[details] 1400/3846 enriched and checkpointed
[details] 1500/3846 enriched and checkpointed
[details] 1600/3846 enriched and checkpointed
[details] 1700/3846 enriched and checkpointed
[details] 1800/3846 enriched and checkpointed
[details] 1900/3846 enriched and checkpointed
[details] 2000/3846 enriched and checkpointed
[details] 2100/3846 enriched and checkpointed
[details] 2200/3846 enriched and checkpointed
[details] 2300/3846 enriched and checkpointed
[details] 2400/3846 enriched and checkpointed
[details] 2500/3846 enriched and checkpointed
[details] 2600/3846 enriched and checkpointed
[details] 2700/3846 enriched and checkpointed
[details] 2800/3846 enriched and checkpointed
[details] 2900/3846 enriched and checkpointed
[details] 3000/3846 enriched and checkpointed
[details] 3100/3846 enriched and checkpointed
[details] 3200/3846 enriched and checkpointed
[details] 3300/3846 enriched and checkpointed
[details] 3400/3846 enriched and checkpointed
[details] 3500/3846 enriched and checkpointed
[details] 3600/3846 enriched and checkpointed
[details] 3700/3846 enriched and checkpointed
[details] 3800/3846 enriched and checkpointed
[details] enrichment finished and checkpointed

=== Totals after this type ===
Places by category:
 category
restaurant            3375
tourist attraction     464
shopping mall            4
park                     3
Name: place_id, dtype: int64

Reviews by category:
 category
restaurant            15539
tourist attraction     1903
shopping mall            20
park                     15
Name: review_id, dtype: int64

In [97]:
# ==== SET THESE TWO AND RUN ====
CURRENT_TYPE = "park"      # then "park then "shopping_mall"
TAG          = "grid_classic_park"  # then "grid_classic_park", "grid_classic_shopping_mall"

# 1) Crawl grid (resume-safe, checkpointed)
df_type = crawl_grid_for_type_classic_checkpointed(CURRENT_TYPE, centers, checkpoint_every=30, resume=True)
print(f"Unique {CURRENT_TYPE} discovered this run:", df_type["place_id"].nunique())

# 2) Merge into basic list
import pandas as pd
from pathlib import Path

PLACES_BASIC_CSV   = "data/processed/auckland_places_basic.csv"
PLACES_DETAILS_CSV = "data/processed/auckland_places_details.csv"
REVIEWS_CSV        = "data/processed/auckland_reviews.csv"

places_basic = pd.read_csv(PLACES_BASIC_CSV) if Path(PLACES_BASIC_CSV).exists() else pd.DataFrame()
df_basic_merged = (pd.concat([places_basic, df_type], ignore_index=True)
                   .dropna(subset=["place_id"])
                   .drop_duplicates("place_id")
                   .reset_index(drop=True))
df_basic_merged.to_csv(PLACES_BASIC_CSV, index=False)

# 3) Enrich ONLY new place_ids (resume-safe)
places_details_existing = pd.read_csv(PLACES_DETAILS_CSV) if Path(PLACES_DETAILS_CSV).exists() else pd.DataFrame()
existing_ids = set(places_details_existing["place_id"]) if not places_details_existing.empty else set()
new_ids = [pid for pid in df_basic_merged["place_id"].tolist() if pid not in existing_ids]

# Skip IDs already checkpointed for this TAG
from pathlib import Path
det_ckpt = Path(f"data/checkpoints/details_{TAG}.csv")
done_ids = set(pd.read_csv(det_ckpt, usecols=["place_id"])["place_id"]) if det_ckpt.exists() else set()

remaining_ids = [pid for pid in new_ids if pid not in done_ids]
print(f"Remaining to enrich ({CURRENT_TYPE}):", len(remaining_ids))

enrich_only_new_with_checkpoint(remaining_ids, tag=TAG, chunk=100)

# 4) Combine checkpoint results back into main CSVs
def infer_category_priority(types_str):
    """Map Google's many types into your 5 buckets with a clear priority."""
    if pd.isna(types_str): return None
    t = {x.strip().lower() for x in str(types_str).split(",")}
    # priority: malls > tourist attractions > parks > restaurants > cafes
    if "shopping_mall" in t or "shopping mall" in t: return "shopping mall"
    if "tourist_attraction" in t or "tourist attraction" in t: return "tourist attraction"
    if "park" in t: return "park"
    if {"restaurant","meal_takeaway","meal_delivery","fast_food"} & t: return "restaurant"
    if {"cafe","coffee_shop","café"} & t: return "cafe"
    return None

def combine_back_into_main(tag):
    import pandas as pd
    from pathlib import Path
    CKPT = Path("data/checkpoints")

    det_ckpt = CKPT / f"details_{tag}.csv"
    if det_ckpt.exists():
        df_new_det = pd.read_csv(det_ckpt)
        # normalize category
        df_new_det["category"] = df_new_det["types"].apply(infer_category_priority)
        if Path(PLACES_DETAILS_CSV).exists():
            df_det_old = pd.read_csv(PLACES_DETAILS_CSV)
            df_det_all = (pd.concat([df_det_old, df_new_det], ignore_index=True)
                          .dropna(subset=["place_id"])
                          .drop_duplicates("place_id")
                          .reset_index(drop=True))
        else:
            df_det_all = df_new_det
        df_det_all.to_csv(PLACES_DETAILS_CSV, index=False)

    rev_ckpt = CKPT / f"reviews_{tag}.csv"
    if rev_ckpt.exists():
        df_new_rev = pd.read_csv(rev_ckpt)
        if "review_id" not in df_new_rev.columns:
            import hashlib
            df_new_rev["text"] = df_new_rev["text"].fillna("")
            df_new_rev["review_id"] = df_new_rev.apply(
                lambda r: hashlib.sha256(f"{r.get('place_id','')}|{r.get('time','')}|{r.get('text','')[:32]}".encode("utf-8")).hexdigest()[:24],
                axis=1
            )
        if Path(REVIEWS_CSV).exists():
            df_rev_old = pd.read_csv(REVIEWS_CSV)
            df_rev_all = (pd.concat([df_rev_old, df_new_rev], ignore_index=True)
                          .dropna(subset=["place_id"])
                          .drop_duplicates(subset=["review_id"])
                          .reset_index(drop=True))
        else:
            df_rev_all = df_new_rev
        df_rev_all.to_csv(REVIEWS_CSV, index=False)

combine_back_into_main(TAG)

# 5) Print fresh totals
def by_cat_places(df):
    if df.empty: return pd.Series(dtype=int)
    tmp = df.dropna(subset=["place_id"]).drop_duplicates("place_id")
    if "category" not in tmp.columns or tmp["category"].isna().all():
        tmp["category"] = tmp["types"].apply(infer_category_priority)
    return tmp.groupby("category")["place_id"].nunique().sort_values(ascending=False)

def by_cat_reviews(rev, places_df):
    if rev.empty: return pd.Series(dtype=int)
    tmp = rev.merge(places_df[["place_id","types","category"]], on="place_id", how="left")
    if "category" not in tmp.columns or tmp["category"].isna().all():
        tmp["category"] = tmp["types"].apply(infer_category_priority)
    key = "review_id" if "review_id" in tmp.columns else tmp.columns[0]
    return tmp.groupby("category")[key].count().sort_values(ascending=False)

places_details_updated = pd.read_csv(PLACES_DETAILS_CSV) if Path(PLACES_DETAILS_CSV).exists() else pd.DataFrame()
reviews_updated       = pd.read_csv(REVIEWS_CSV)        if Path(REVIEWS_CSV).exists() else pd.DataFrame()

print("\n=== Totals after this type ===")
print("Places by category:\n", by_cat_places(places_details_updated).fillna(0), "\n")
print("Reviews by category:\n", by_cat_reviews(reviews_updated, places_details_updated).fillna(0), "\n")

[park] Resume from center #0 (seen_ids=0)
[park] checkpoint at center #30 | seen_ids=27 | saved to data\checkpoints\nearby_rows_park.csv
[park] checkpoint at center #60 | seen_ids=156 | saved to data\checkpoints\nearby_rows_park.csv
[park] checkpoint at center #90 | seen_ids=264 | saved to data\checkpoints\nearby_rows_park.csv
[park] checkpoint at center #120 | seen_ids=420 | saved to data\checkpoints\nearby_rows_park.csv
[park] checkpoint at center #150 | seen_ids=766 | saved to data\checkpoints\nearby_rows_park.csv
[park] checkpoint at center #180 | seen_ids=1098 | saved to data\checkpoints\nearby_rows_park.csv
[park] checkpoint at center #210 | seen_ids=1607 | saved to data\checkpoints\nearby_rows_park.csv
[park] checkpoint at center #240 | seen_ids=1827 | saved to data\checkpoints\nearby_rows_park.csv
[park] checkpoint at center #270 | seen_ids=2017 | saved to data\checkpoints\nearby_rows_park.csv
[park] checkpoint at center #300 | seen_ids=2225 | saved to data\checkpoints\nearby_rows_park.csv
[park] checkpoint at center #330 | seen_ids=2295 | saved to data\checkpoints\nearby_rows_park.csv
[park] checkpoint at center #360 | seen_ids=2338 | saved to data\checkpoints\nearby_rows_park.csv
[park] checkpoint at center #390 | seen_ids=2376 | saved to data\checkpoints\nearby_rows_park.csv
[park] finished crawl | total seen_ids=2443 | checkpoints in data\checkpoints
Unique park discovered this run: 2443
Remaining to enrich (park): 2257
[details] 100/2257 enriched and checkpointed
[details] 200/2257 enriched and checkpointed
[details] 300/2257 enriched and checkpointed
[details] 400/2257 enriched and checkpointed
[details] 500/2257 enriched and checkpointed
[details] 600/2257 enriched and checkpointed
[details] 700/2257 enriched and checkpointed
[details] 800/2257 enriched and checkpointed
[details] 900/2257 enriched and checkpointed
[details] 1000/2257 enriched and checkpointed
[details] 1100/2257 enriched and checkpointed
[details] 1200/2257 enriched and checkpointed
[details] 1300/2257 enriched and checkpointed
[details] 1400/2257 enriched and checkpointed
[details] 1500/2257 enriched and checkpointed
[details] 1600/2257 enriched and checkpointed
[details] 1700/2257 enriched and checkpointed
[details] 1800/2257 enriched and checkpointed
[details] 1900/2257 enriched and checkpointed
[details] 2000/2257 enriched and checkpointed
[details] 2100/2257 enriched and checkpointed
[details] 2200/2257 enriched and checkpointed
[details] enrichment finished and checkpointed

=== Totals after this type ===
Places by category:
 category
restaurant            3375
park                  2259
tourist attraction     465
shopping mall            4
Name: place_id, dtype: int64

Reviews by category:
 category
restaurant            15539
park                   6913
tourist attraction     1908
shopping mall            20
Name: review_id, dtype: int64

In [99]:
# ==== SET THESE TWO AND RUN ====
CURRENT_TYPE = "shopping_mall"      
TAG          = "grid_classic_shopping_mall"  

# 1) Crawl grid (resume-safe, checkpointed)
df_type = crawl_grid_for_type_classic_checkpointed(CURRENT_TYPE, centers, checkpoint_every=30, resume=True)
print(f"Unique {CURRENT_TYPE} discovered this run:", df_type["place_id"].nunique())

# 2) Merge into basic list
import pandas as pd
from pathlib import Path

PLACES_BASIC_CSV   = "data/processed/auckland_places_basic.csv"
PLACES_DETAILS_CSV = "data/processed/auckland_places_details.csv"
REVIEWS_CSV        = "data/processed/auckland_reviews.csv"

places_basic = pd.read_csv(PLACES_BASIC_CSV) if Path(PLACES_BASIC_CSV).exists() else pd.DataFrame()
df_basic_merged = (pd.concat([places_basic, df_type], ignore_index=True)
                   .dropna(subset=["place_id"])
                   .drop_duplicates("place_id")
                   .reset_index(drop=True))
df_basic_merged.to_csv(PLACES_BASIC_CSV, index=False)

# 3) Enrich ONLY new place_ids (resume-safe)
places_details_existing = pd.read_csv(PLACES_DETAILS_CSV) if Path(PLACES_DETAILS_CSV).exists() else pd.DataFrame()
existing_ids = set(places_details_existing["place_id"]) if not places_details_existing.empty else set()
new_ids = [pid for pid in df_basic_merged["place_id"].tolist() if pid not in existing_ids]

# Skip IDs already checkpointed for this TAG
from pathlib import Path
det_ckpt = Path(f"data/checkpoints/details_{TAG}.csv")
done_ids = set(pd.read_csv(det_ckpt, usecols=["place_id"])["place_id"]) if det_ckpt.exists() else set()

remaining_ids = [pid for pid in new_ids if pid not in done_ids]
print(f"Remaining to enrich ({CURRENT_TYPE}):", len(remaining_ids))

enrich_only_new_with_checkpoint(remaining_ids, tag=TAG, chunk=100)

# 4) Combine checkpoint results back into main CSVs
def infer_category_priority(types_str):
    """Map Google's many types into your 5 buckets with a clear priority."""
    if pd.isna(types_str): return None
    t = {x.strip().lower() for x in str(types_str).split(",")}
    # priority: malls > tourist attractions > parks > restaurants > cafes
    if "shopping_mall" in t or "shopping mall" in t: return "shopping mall"
    if "tourist_attraction" in t or "tourist attraction" in t: return "tourist attraction"
    if "park" in t: return "park"
    if {"restaurant","meal_takeaway","meal_delivery","fast_food"} & t: return "restaurant"
    if {"cafe","coffee_shop","café"} & t: return "cafe"
    return None

def combine_back_into_main(tag):
    import pandas as pd
    from pathlib import Path
    CKPT = Path("data/checkpoints")

    det_ckpt = CKPT / f"details_{tag}.csv"
    if det_ckpt.exists():
        df_new_det = pd.read_csv(det_ckpt)
        # normalize category
        df_new_det["category"] = df_new_det["types"].apply(infer_category_priority)
        if Path(PLACES_DETAILS_CSV).exists():
            df_det_old = pd.read_csv(PLACES_DETAILS_CSV)
            df_det_all = (pd.concat([df_det_old, df_new_det], ignore_index=True)
                          .dropna(subset=["place_id"])
                          .drop_duplicates("place_id")
                          .reset_index(drop=True))
        else:
            df_det_all = df_new_det
        df_det_all.to_csv(PLACES_DETAILS_CSV, index=False)

    rev_ckpt = CKPT / f"reviews_{tag}.csv"
    if rev_ckpt.exists():
        df_new_rev = pd.read_csv(rev_ckpt)
        if "review_id" not in df_new_rev.columns:
            import hashlib
            df_new_rev["text"] = df_new_rev["text"].fillna("")
            df_new_rev["review_id"] = df_new_rev.apply(
                lambda r: hashlib.sha256(f"{r.get('place_id','')}|{r.get('time','')}|{r.get('text','')[:32]}".encode("utf-8")).hexdigest()[:24],
                axis=1
            )
        if Path(REVIEWS_CSV).exists():
            df_rev_old = pd.read_csv(REVIEWS_CSV)
            df_rev_all = (pd.concat([df_rev_old, df_new_rev], ignore_index=True)
                          .dropna(subset=["place_id"])
                          .drop_duplicates(subset=["review_id"])
                          .reset_index(drop=True))
        else:
            df_rev_all = df_new_rev
        df_rev_all.to_csv(REVIEWS_CSV, index=False)

combine_back_into_main(TAG)

# 5) Print fresh totals
def by_cat_places(df):
    if df.empty: return pd.Series(dtype=int)
    tmp = df.dropna(subset=["place_id"]).drop_duplicates("place_id")
    if "category" not in tmp.columns or tmp["category"].isna().all():
        tmp["category"] = tmp["types"].apply(infer_category_priority)
    return tmp.groupby("category")["place_id"].nunique().sort_values(ascending=False)

def by_cat_reviews(rev, places_df):
    if rev.empty: return pd.Series(dtype=int)
    tmp = rev.merge(places_df[["place_id","types","category"]], on="place_id", how="left")
    if "category" not in tmp.columns or tmp["category"].isna().all():
        tmp["category"] = tmp["types"].apply(infer_category_priority)
    key = "review_id" if "review_id" in tmp.columns else tmp.columns[0]
    return tmp.groupby("category")[key].count().sort_values(ascending=False)

places_details_updated = pd.read_csv(PLACES_DETAILS_CSV) if Path(PLACES_DETAILS_CSV).exists() else pd.DataFrame()
reviews_updated       = pd.read_csv(REVIEWS_CSV)        if Path(REVIEWS_CSV).exists() else pd.DataFrame()

print("\n=== Totals after this type ===")
print("Places by category:\n", by_cat_places(places_details_updated).fillna(0), "\n")
print("Reviews by category:\n", by_cat_reviews(reviews_updated, places_details_updated).fillna(0), "\n")

[shopping_mall] Resume from center #0 (seen_ids=0)
[shopping_mall] checkpoint at center #30 | seen_ids=1 | saved to data\checkpoints\nearby_rows_shopping_mall.csv
[shopping_mall] checkpoint at center #60 | seen_ids=7 | saved to data\checkpoints\nearby_rows_shopping_mall.csv
[shopping_mall] checkpoint at center #90 | seen_ids=11 | saved to data\checkpoints\nearby_rows_shopping_mall.csv
[shopping_mall] checkpoint at center #120 | seen_ids=26 | saved to data\checkpoints\nearby_rows_shopping_mall.csv
[shopping_mall] checkpoint at center #150 | seen_ids=49 | saved to data\checkpoints\nearby_rows_shopping_mall.csv
[shopping_mall] checkpoint at center #180 | seen_ids=81 | saved to data\checkpoints\nearby_rows_shopping_mall.csv
[shopping_mall] checkpoint at center #210 | seen_ids=140 | saved to data\checkpoints\nearby_rows_shopping_mall.csv
[shopping_mall] checkpoint at center #240 | seen_ids=149 | saved to data\checkpoints\nearby_rows_shopping_mall.csv
[shopping_mall] checkpoint at center #270 | seen_ids=162 | saved to data\checkpoints\nearby_rows_shopping_mall.csv
[shopping_mall] checkpoint at center #300 | seen_ids=170 | saved to data\checkpoints\nearby_rows_shopping_mall.csv
[shopping_mall] checkpoint at center #330 | seen_ids=176 | saved to data\checkpoints\nearby_rows_shopping_mall.csv
[shopping_mall] checkpoint at center #360 | seen_ids=177 | saved to data\checkpoints\nearby_rows_shopping_mall.csv
[shopping_mall] checkpoint at center #390 | seen_ids=180 | saved to data\checkpoints\nearby_rows_shopping_mall.csv
[shopping_mall] finished crawl | total seen_ids=184 | checkpoints in data\checkpoints
Unique shopping_mall discovered this run: 184
Remaining to enrich (shopping_mall): 120
[details] 100/120 enriched and checkpointed
[details] enrichment finished and checkpointed

=== Totals after this type ===
Places by category:
 category
restaurant            3375
park                  2259
tourist attraction     465
shopping mall          124
Name: place_id, dtype: int64

Reviews by category:
 category
restaurant            15539
park                   6913
tourist attraction     1908
shopping mall           422
Name: review_id, dtype: int64

In [101]:
import pandas as pd
from pathlib import Path
import hashlib

CKPT = Path("data/checkpoints")
PLACES_BASIC   = Path("data/processed/auckland_places_basic.csv")
PLACES_DETAILS = Path("data/processed/auckland_places_details.csv")
REVIEWS        = Path("data/processed/auckland_reviews.csv")

# 1) Merge all nearby “basic” rows found during grid runs
nearby_frames = []
for t in ["restaurant","cafe","tourist_attraction","park","shopping_mall"]:
    f = CKPT / f"nearby_rows_{t}.csv"
    if f.exists():
        nearby_frames.append(pd.read_csv(f))
if nearby_frames:
    df_basic_ckpt = (pd.concat(nearby_frames, ignore_index=True)
                     .dropna(subset=["place_id"])
                     .drop_duplicates("place_id"))
    if PLACES_BASIC.exists():
        df_basic_all = pd.concat([pd.read_csv(PLACES_BASIC), df_basic_ckpt], ignore_index=True)
    else:
        df_basic_all = df_basic_ckpt
    df_basic_all = df_basic_all.dropna(subset=["place_id"]).drop_duplicates("place_id").reset_index(drop=True)
    df_basic_all.to_csv(PLACES_BASIC, index=False)

# 2) Merge details and reviews from each tag
TAGS = [
    "grid_classic_restaurant",
    "grid_classic_cafe",
    "grid_classic_tourist_attraction",
    "grid_classic_park",
    "grid_classic_shopping_mall",
]
det_frames, rev_frames = [], []
for tag in TAGS:
    det = CKPT / f"details_{tag}.csv"
    rev = CKPT / f"reviews_{tag}.csv"
    if det.exists(): det_frames.append(pd.read_csv(det))
    if rev.exists(): rev_frames.append(pd.read_csv(rev))

if det_frames:
    df_det_ckpt = (pd.concat(det_frames, ignore_index=True)
                   .dropna(subset=["place_id"])
                   .drop_duplicates("place_id"))
    if PLACES_DETAILS.exists():
        df_det_all = pd.concat([pd.read_csv(PLACES_DETAILS), df_det_ckpt], ignore_index=True)
    else:
        df_det_all = df_det_ckpt
    df_det_all = df_det_all.dropna(subset=["place_id"]).drop_duplicates("place_id").reset_index(drop=True)
else:
    df_det_all = pd.read_csv(PLACES_DETAILS) if PLACES_DETAILS.exists() else pd.DataFrame()

if rev_frames:
    df_rev_ckpt = pd.concat(rev_frames, ignore_index=True)
    if "review_id" not in df_rev_ckpt.columns:
        df_rev_ckpt["text"] = df_rev_ckpt["text"].fillna("")
        df_rev_ckpt["review_id"] = df_rev_ckpt.apply(
            lambda r: hashlib.sha256(f"{r.get('place_id','')}|{r.get('time','')}|{r.get('text','')[:32]}".encode()).hexdigest()[:24],
            axis=1
        )
    if REVIEWS.exists():
        df_rev_all = pd.concat([pd.read_csv(REVIEWS), df_rev_ckpt], ignore_index=True)
    else:
        df_rev_all = df_rev_ckpt
    df_rev_all = (df_rev_all
                  .dropna(subset=["place_id"])
                  .drop_duplicates(subset=["review_id"])
                  .reset_index(drop=True))
else:
    df_rev_all = pd.read_csv(REVIEWS) if REVIEWS.exists() else pd.DataFrame()

# Normalize to your 5 categories with a simple priority
def map_to_category(types_str):
    if pd.isna(types_str): return None
    t = {x.strip().lower() for x in str(types_str).split(",")}
    if "shopping_mall" in t or "shopping mall" in t: return "shopping mall"
    if "tourist_attraction" in t or "tourist attraction" in t: return "tourist attraction"
    if "park" in t: return "park"
    if {"restaurant","meal_takeaway","meal_delivery","fast_food"} & t: return "restaurant"
    if {"cafe","coffee_shop","café"} & t: return "cafe"
    return None

if not df_det_all.empty:
    df_det_all["category"] = df_det_all["types"].apply(map_to_category)

# Save consolidated main CSVs
df_det_all.to_csv(PLACES_DETAILS, index=False)
df_rev_all.to_csv(REVIEWS, index=False)

print("Consolidated:")
print("  places_basic:", PLACES_BASIC.exists())
print("  places_details rows:", len(df_det_all), "unique places:", df_det_all['place_id'].nunique() if 'place_id' in df_det_all else 0)
print("  reviews rows:", len(df_rev_all))

Consolidated:
  places_basic: True
  places_details rows: 6506 unique places: 6506
  reviews rows: 24805

In [103]:
from pathlib import Path
import pandas as pd

PLACES_DETAILS = Path("data/processed/auckland_places_details.csv")
REVIEWS        = Path("data/processed/auckland_reviews.csv")

places = pd.read_csv(PLACES_DETAILS)
reviews = pd.read_csv(REVIEWS)

# Drop places without coordinates or category
places = places.dropna(subset=["lat","lng"])
if "category" not in places.columns:
    places["category"] = places["types"].apply(map_to_category)
places = places[places["category"].notna()]

# (Optional) stability filter: keep places with >= 5 total ratings
if "user_ratings_total" in places.columns:
    places["user_ratings_total"] = pd.to_numeric(places["user_ratings_total"], errors="coerce").fillna(0).astype(int)
    places = places[places["user_ratings_total"] >= 5]

# Keep only reviews for kept places
keep_ids = set(places["place_id"])
reviews = reviews[reviews["place_id"].isin(keep_ids)]

# Freeze a versioned snapshot
Path("data/final").mkdir(parents=True, exist_ok=True)
places.to_csv("data/final/places.csv", index=False)
reviews.to_csv("data/final/reviews.csv", index=False)

print("Final snapshot saved → data/final/places.csv & data/final/reviews.csv")
print("Final unique places:", places['place_id'].nunique(), "Final reviews:", len(reviews))
print("\nPlaces by category:\n", places.groupby("category")["place_id"].nunique().sort_values(ascending=False))

Final snapshot saved → data/final/places.csv & data/final/reviews.csv
Final unique places: 4840 Final reviews: 22853

Places by category:
 category
restaurant            3131
park                  1122
tourist attraction     432
shopping mall          132
cafe                    23
Name: place_id, dtype: int64

In [105]:
def map_to_category(types_str):
    """
    Collapse Google's many types into your final 4 buckets:
      - restaurant (includes cafe/coffee_shop/fast_food/meal_takeaway/meal_delivery)
      - tourist attraction
      - park
      - shopping mall
    """
    if pd.isna(types_str): 
        return None
    t = {x.strip().lower() for x in str(types_str).split(",")}

    if "shopping_mall" in t or "shopping mall" in t:
        return "shopping mall"
    if "tourist_attraction" in t or "tourist attraction" in t:
        return "tourist attraction"
    if "park" in t:
        return "park"

    # Everything “food & drink” incl. cafes → restaurant
    if {"restaurant","cafe","coffee_shop","café","fast_food","meal_takeaway","meal_delivery"} & t:
        return "restaurant"

    return None

In [107]:
import pandas as pd
from pathlib import Path

PLACES_DETAILS = Path("data/processed/auckland_places_details.csv")
REVIEWS        = Path("data/processed/auckland_reviews.csv")

places = pd.read_csv(PLACES_DETAILS) if PLACES_DETAILS.exists() else pd.DataFrame()
reviews = pd.read_csv(REVIEWS) if REVIEWS.exists() else pd.DataFrame()

# Recompute category from 'types' using the new mapper
places["category"] = places["types"].apply(map_to_category)

# Optional QC: drop rows with no category / missing coords
places = places.dropna(subset=["lat","lng"])
places = places[places["category"].notna()]

# Keep only reviews for kept places
keep_ids = set(places["place_id"])
reviews = reviews[reviews["place_id"].isin(keep_ids)]

# Save back (processed) and also freeze final copies
places.to_csv(PLACES_DETAILS, index=False)
reviews.to_csv(REVIEWS, index=False)

Path("data/final").mkdir(parents=True, exist_ok=True)
places.to_csv("data/final/places.csv", index=False)
reviews.to_csv("data/final/reviews.csv", index=False)

print("Saved with 4 categories. Totals:")
print("Unique places:", places["place_id"].nunique(), " | Reviews:", len(reviews))
print("\nPlaces by category:")
print(places.groupby("category")["place_id"].nunique().sort_values(ascending=False))

Saved with 4 categories. Totals:
Unique places: 6501  | Reviews: 24805

Places by category:
category
restaurant            3491
park                  2283
tourist attraction     543
shopping mall          184
Name: place_id, dtype: int64

In [109]:
# Create a clean hand-off for NLP
import pandas as pd, hashlib, pathlib, re

reviews = pd.read_csv("data/final/reviews.csv")

# Ensure review_id exists (stable hash of place_id + time + text head)
if "review_id" not in reviews.columns:
    reviews["text"] = reviews["text"].fillna("")
    reviews["review_id"] = reviews.apply(
        lambda r: hashlib.sha256(f"{r.get('place_id','')}|{r.get('time','')}|{(r.get('text','')[:32])}".encode("utf-8")).hexdigest()[:24],
        axis=1
    )

# Clean text: drop newlines/tabs and trim
reviews["text"] = reviews["text"].fillna("").str.replace(r"\s+", " ", regex=True).str.strip()

# Keep only the columns NLP needs (whatever exists among these)
keep_cols = [c for c in ["review_id","place_id","text","rating","time","language"] if c in reviews.columns]
nlp_input = reviews[keep_cols].copy()

# Save
pathlib.Path("handoff").mkdir(parents=True, exist_ok=True)
nlp_input.to_csv("handoff/nlp_input_reviews.csv", index=False, encoding="utf-8")

print("Wrote handoff/nlp_input_reviews.csv")
print("Rows:", len(nlp_input))
print("Sample:")
display(nlp_input.head(3))

Wrote handoff/nlp_input_reviews.csv
Rows: 24805
Sample:

,review_id,place_id,text,rating,time,language
0,NaN,ChIJF2_wv4lHDW0R47WKR5aSdmE,Fabulous Food! Enjoyed an outstanding food per...,5,1754804453,en
1,385c974be3592a045667e1e1,ChIJY5ETuM2gEm0RFg6D9SQ6qsE,Wonderful little store with an amazing variety...,5,1706345529,en
2,0977732e5142d7a603182a63,ChIJY5ETuM2gEm0RFg6D9SQ6qsE,Bhanas is the type of store that makes you fee...,5,1504729714,en

In [111]:
import pandas as pd, hashlib, os, re, pathlib

PATH = "handoff/nlp_input_reviews.csv"
df = pd.read_csv(PATH)

# 1) Ensure text is single-line + trimmed
df["text"] = df["text"].fillna("").str.replace(r"\s+", " ", regex=True).str.strip()

# 2) Fill missing/blank review_id, and make sure ALL ids are unique
def make_id(row):
    base = f"{row.get('place_id','')}|{row.get('time','')}|{row.get('text','')[:64]}"
    return hashlib.sha256(base.encode("utf-8")).hexdigest()[:24]

# create id where missing/blank
if "review_id" not in df.columns:
    df["review_id"] = df.apply(make_id, axis=1)
else:
    mask = df["review_id"].isna() | (df["review_id"].astype(str).str.strip() == "")
    df.loc[mask, "review_id"] = df[mask].apply(make_id, axis=1)

# dedupe exact duplicates by (review_id); if collisions remain, re-hash with row index
dups = df["review_id"].duplicated(keep=False)
if dups.any():
    colliders = df.loc[dups].copy()
    df.loc[dups, "review_id"] = colliders.apply(
        lambda r: hashlib.sha256(f"{r['review_id']}|{r.name}".encode("utf-8")).hexdigest()[:24], axis=1
    )

# 3) Minimal sanity checks
print("Rows:", len(df))
print("Unique review_id:", df["review_id"].nunique())
print("Missing review_id:", df["review_id"].isna().sum())

# 4) Save back (overwrite)
df.to_csv(PATH, index=False, encoding="utf-8")

# 5) File size
mb = round(os.path.getsize(PATH)/1_048_576, 2)
print("Saved:", PATH, "| Size (MB):", mb)

Rows: 24805
Unique review_id: 24805
Missing review_id: 0
Saved: handoff/nlp_input_reviews.csv | Size (MB): 8.18